"""
Tests for Escape Hatch Wiring in AST Translation.
"""

import pytest
from typing import Set

from ml_switcheroo.core.engine import ASTEngine
from ml_switcheroo.semantics.manager import SemanticsManager
from ml_switcheroo.core.escape_hatch import EscapeHatch


class MockSemantics(SemanticsManager):
  def __init__(self):
    # Define data explicitly
    self.data = {
      "abs": {"variants": {"torch": {"api": "torch.abs"}, "jax": {"api": "jax.numpy.abs"}}},
      "DataLoader": {
        "std_args": ["dataset"],
        "variants": {
          "torch": {"api": "torch.utils.data.DataLoader"},
          "jax": None,  # Trigger Escape Hatch
        },
      },
    }
    self.import_data = {}
    self.framework_configs = {}
    # FIX: Initialize required RNG set for PurityScanner
    self._known_rng_methods = {"seed", "manual_seed"}

    self._reverse_index = {
      "torch.abs": ("abs", self.data["abs"]),
      "torch.utils.data.DataLoader": ("DataLoader", self.data["DataLoader"]),
    }

  # FIX: Implement required method for PurityScanner
  def get_all_rng_methods(self) -> Set[str]:
    return self._known_rng_methods

  def get_definition(self, name):
    # STRICT lookup to avoid "abs" matching "torch.utils"
    return self._reverse_index.get(name)

  def resolve_variant(self, abstract_id, target_fw):
    defn = self.data.get(abstract_id)
    if not defn:
      return None
    return defn["variants"].get(target_fw)

  def is_verified(self, _id):
    return True


@pytest.fixture
def semantics_mgr():
  return MockSemantics()


def test_escape_hatch_tier_c_gap(semantics_mgr):
  # Enable strict mode to force the rewriter to complain about the missing JAX variant
  engine = ASTEngine(semantics=semantics_mgr, source="torch", target="jax", strict_mode=True)

  code = "loader = torch.utils.data.DataLoader(ds)"
  result = engine.run(code)

  assert "torch.utils.data.DataLoader(ds)" in result.code
  assert "loader =" in result.code
  # Expect error because JAX variant is None
  assert len(result.errors) >= 1
  # The generic error message generated by the Engine when hatch markers are found
  assert "Escape Hatches Detected" in result.errors[0]


def test_strict_mode_unknown_source_api(semantics_mgr):
  engine = ASTEngine(semantics=semantics_mgr, source="torch", target="jax", strict_mode=True)
  code = "y = torch.weird_custom_func(x)"
  result = engine.run(code)

  assert "torch.weird_custom_func(x)" in result.code
  assert result.has_errors is True


def test_strict_mode_ignores_standard_python(semantics_mgr):
  # 'len' is not in reverse index, calls get_definition -> returns None -> Passthrough
  # Since it doesn't start with 'torch.', strict mode ignores it in base rewriter logic
  engine = ASTEngine(semantics=semantics_mgr, source="torch", target="jax", strict_mode=True)
  code = "z = len(x)"
  result = engine.run(code)

  assert EscapeHatch.START_MARKER not in result.code
  assert "z = len(x)" in result.code
  assert result.has_errors is False


def test_default_mode_passthrough(semantics_mgr):
  engine = ASTEngine(semantics=semantics_mgr, source="torch", target="jax", strict_mode=False)
  code = "y = torch.weird_custom_func(x)"
  result = engine.run(code)

  assert EscapeHatch.START_MARKER not in result.code
  assert "torch.weird_custom_func(x)" in result.code
  assert result.has_errors is False
