"""
SASS Emitter.

This module provides the `SassEmitter` class, which is responsible for the final
stage of the SASS compilation pipeline: converting the Abstract Syntax Tree (AST)
nodes (Instructions, Labels, Comments) into formatted text strings valid for
the NVIDIA SASS assembler (or readable verification output).

Capabilities:
1.  **Indentation**: Labels are flush-left; Instructions, Directives, and Comments are indented.
2.  **Formatting**: Delegates string conversion to the specific node's `__str__` method.
3.  **Fallback Rendering**: Ensures comments generated by unmapped operations are rendered correctly.
"""

from typing import List

from ml_switcheroo.core.sass.nodes import Label, SassNode


class SassEmitter:
  """
  Converts SASS AST nodes into textual assembly code.
  """

  def emit(self, nodes: List[SassNode]) -> str:
    """
    Generates the SASS source string from a list of nodes.

    formatting Rules:
    - Labels (e.g. `L_1:`) are rendered flush-left (no indentation).
    - All other nodes (Instructions, Comments, Directives) are indented by 4 spaces.
    - Each node occupies one line.

    Args:
        nodes: A list of SASS AST nodes (e.g. from `SassSynthesizer`).

    Returns:
        The formatted SASS source code string.
    """
    lines = []
    for node in nodes:
      # Labels flush left, everything else indented
      prefix = "" if isinstance(node, Label) else "    "
      line = f"{prefix}{str(node)}"
      lines.append(line)

    # Ensure file ends with newline
    return "\n".join(lines) + "\n"
