[tox]
envlist = py310, py311, py312, py313, py314
isolated_build = True

[testenv]
deps =
    -r requirements.txt
    -r docs/docs-requirements.txt
    -r test-requirements.txt
extras =
    test
commands =
    pytest -n auto --durations=10 tests {posargs}

[testenv:py312]
deps =
    -r requirements.txt
    -r docs/docs-requirements.txt
    -r test-requirements.txt
extras =
    test
commands =
    pytest -n auto --durations=10 --cov=src --cov-fail-under=100 tests {posargs}
    mypy --strict src
    interrogate -c pyproject.toml --fail-under 100
