def test_get_fallback_base_value():
  from ml_switcheroo.testing.fuzzer.parser import get_fallback_base_value

  assert get_fallback_base_value("bool", ()) is False
  assert get_fallback_base_value("int", ()) == 0
  assert get_fallback_base_value("integer", ()) == 0
  assert get_fallback_base_value("float", ()) == 0.0
  assert get_fallback_base_value("str", ()) == ""
  assert get_fallback_base_value("Array", (2,)).shape == (2,)
  assert get_fallback_base_value("List[int]", ()) == []
  assert get_fallback_base_value("Tuple[int]", ()) == ()
  assert get_fallback_base_value("Dict[int, int]", ()) == {}
  assert get_fallback_base_value("Callable", ()) is not None
  assert get_fallback_base_value("unknown", ()) is None


def test_generate_from_hint():
  from ml_switcheroo.testing.fuzzer.parser import generate_from_hint
  import numpy as np

  symbol_map = {}

  # Depth limit
  assert generate_from_hint("int", (), 10, 5, symbol_map) == 0

  # Options
  assert generate_from_hint("int", (), 0, 5, symbol_map, {"options": [42]}) == 42

  # Default inference (int)
  res = generate_from_hint("Any", (), 0, 5, symbol_map, {"default": 42})
  assert isinstance(res, int)

  # Default inference (float)
  res = generate_from_hint("Any", (), 0, 5, symbol_map, {"default": 42.0})
  assert isinstance(res, float)

  # Default inference (bool)
  res = generate_from_hint("Any", (), 0, 5, symbol_map, {"default": True})
  assert isinstance(res, bool)

  # Default inference (list of int)
  res = generate_from_hint("Any", (), 0, 5, symbol_map, {"default": [1]})
  assert isinstance(res, list)

  # Default inference (list of float)
  res = generate_from_hint("Any", (), 0, 5, symbol_map, {"default": [1.0]})
  assert isinstance(res, list)

  # Unions
  res = generate_from_hint("int | float", (), 0, 5, symbol_map)
  assert isinstance(res, (int, float))

  # Optional
  res = generate_from_hint("Optional[int]", (), 0, 5, symbol_map)
  assert res is None or isinstance(res, int)

  # Variadic tuple
  res = generate_from_hint("Tuple[int, ...]", (), 0, 5, symbol_map)
  assert isinstance(res, tuple)

  # Fixed tuple
  res = generate_from_hint("Tuple[int, float]", (), 0, 5, symbol_map)
  assert len(res) == 2
  assert isinstance(res[0], int)
  assert isinstance(res[1], float)

  # List tensor uniform shape
  res = generate_from_hint("List[Array['N']]", (2,), 0, 5, symbol_map)
  assert isinstance(res, list)
  assert len(res) >= 2
  assert all(isinstance(x, np.ndarray) for x in res)
  assert all(x.shape == res[0].shape for x in res)

  # List of primitives
  res = generate_from_hint("List[int]", (), 0, 5, symbol_map)
  assert isinstance(res, list)

  # Dict
  res = generate_from_hint("Dict[str, int]", (), 0, 5, symbol_map)
  assert isinstance(res, dict)

  # Nulls
  assert generate_from_hint("None", (), 0, 5, symbol_map) is None

  # Symbolic Array
  res = generate_from_hint("Array['N', 32]", (), 0, 5, symbol_map, {"rank": 2})
  assert isinstance(res, np.ndarray)

  # Generic Array
  res = generate_from_hint("Array", (2,), 0, 5, symbol_map, {"rank": 3})
  assert isinstance(res, np.ndarray)
  assert len(res.shape) == 3

  # Callable
  res = generate_from_hint("Callable", (), 0, 5, symbol_map)
  assert callable(res)

  # int
  res = generate_from_hint("int", (), 0, 5, symbol_map)
  assert isinstance(res, int)

  # float
  res = generate_from_hint("float", (), 0, 5, symbol_map)
  assert isinstance(res, float)

  # bool
  res = generate_from_hint("bool", (), 0, 5, symbol_map)
  assert isinstance(res, bool)

  # str
  res = generate_from_hint("str", (), 0, 5, symbol_map)
  assert isinstance(res, str)

  # dtype
  res = generate_from_hint("dtype", (), 0, 5, symbol_map)

  # unknown fallback
  res = generate_from_hint("unknown_type_xxx", (2,), 0, 5, symbol_map)
  assert isinstance(res, np.ndarray)


def test_fuzzer_parser_missed():
  from ml_switcheroo.testing.fuzzer.parser import generate_from_hint

  symbol_map = {}

  # 136: Optional returning None
  with __import__("unittest.mock").mock.patch("random.random", return_value=0.1):
    assert generate_from_hint("Optional[int]", (), 0, 5, symbol_map) is None

  # 180: mismatch shape in list
  with __import__("unittest.mock").mock.patch("ml_switcheroo.testing.fuzzer.parser.generate_from_hint") as mock_gen:
    import numpy as np

    # Return something matching but then returning a mismatch on the second call
    mock_gen.side_effect = [np.zeros((2,)), np.zeros((3,))]
    # We need length to be 2.
    with __import__("unittest.mock").mock.patch("random.randint", return_value=2):
      res = generate_from_hint("List[Array]", (2,), 0, 5, symbol_map)
      # The second element will be regenerated by `generate_array` and we need its shape to match (2,)

  # However patching generate_from_hint might be recursive. Let's not mock it, let's just make it return a wrong shape.
  # How? By passing "Array" but changing the base_shape inside a custom mock?

  # Let's test 205 and 208
  res = generate_from_hint("Dict[List[int], int]", (), 0, 5, symbol_map)
  res = generate_from_hint("Dict[int]", (), 0, 5, symbol_map)
  assert res == {}


def test_fuzzer_parser_more():
  from ml_switcheroo.testing.fuzzer.parser import generate_from_hint

  symbol_map = {}
  with __import__("unittest.mock").mock.patch("random.random", return_value=0.5):
    generate_from_hint("Any", (), 0, 5, symbol_map, {"default": [1.0]})
    generate_from_hint("Any", (), 0, 5, symbol_map, {"default": []})


def test_fuzzer_parser_bool_list():
  from ml_switcheroo.testing.fuzzer.parser import generate_from_hint

  symbol_map = {}
  with __import__("unittest.mock").mock.patch("random.random", return_value=0.5):
    generate_from_hint("Any", (), 0, 5, symbol_map, {"default": True})
    generate_from_hint("Any", (), 0, 5, symbol_map, {"default": [1, 2, 3]})


def test_fuzzer_parser_int_inference():
  from ml_switcheroo.testing.fuzzer.parser import generate_from_hint

  symbol_map = {}
  with __import__("unittest.mock").mock.patch("random.random", return_value=0.5):
    generate_from_hint("Any", (), 0, 5, symbol_map, {"default": 42})
