import pytest
import warnings
from ml_switcheroo.enums import SemanticTier
from ml_switcheroo.semantics.schema import PatternDef
from ml_switcheroo.semantics.merging import (
  infer_tier_from_priority,
  merge_frameworks,
  merge_patterns,
  _normalize_args,
  merge_tier_data,
  merge_overlay_data,
)


def test_infer_tier_from_priority():
  assert infer_tier_from_priority(10) == SemanticTier.ARRAY_API
  assert infer_tier_from_priority(20) == SemanticTier.NEURAL
  assert infer_tier_from_priority(99) == SemanticTier.EXTRAS
  assert infer_tier_from_priority(0) == SemanticTier.EXTRAS


def test_merge_frameworks():
  master = {}

  # Empty to start, adding brand new framework
  merge_frameworks(master, {"torch": {"alias": {"x": "y"}, "traits": {"foo": "bar"}}})
  assert "torch" in master
  assert master["torch"]["alias"]["x"] == "y"

  # Merge into existing, updating alias
  merge_frameworks(master, {"torch": {"alias": {"a": "b"}, "other": 1}})
  assert master["torch"]["alias"] == {"x": "y", "a": "b"}
  assert master["torch"]["other"] == 1

  # Merge into existing, overwriting traits
  merge_frameworks(master, {"torch": {"traits": {"new": "val"}}})
  assert master["torch"]["traits"] == {"new": "val"}

  # Merge into existing, generic update
  merge_frameworks(master, {"torch": {"new_key": "new_val"}})
  assert master["torch"]["new_key"] == "new_val"


def test_merge_patterns(capsys):
  master = [PatternDef(name="Existing", sequence=["a"], replace_with="b")]

  # Add a valid new pattern
  merge_patterns(master, [{"name": "NewPat", "sequence": ["x"], "replace_with": "y"}])
  assert len(master) == 2
  assert master[1].name == "NewPat"

  # Add a duplicate pattern
  merge_patterns(master, [{"name": "Existing", "sequence": ["a"], "replace_with": "b"}])
  assert len(master) == 2

  # Add an invalid pattern
  merge_patterns(master, [{"name": "BadPat"}])  # Missing fields
  assert len(master) == 2
  captured = capsys.readouterr()
  assert "Invalid pattern definition:" in captured.out


def test_normalize_args():
  res = _normalize_args(
    ["simple_str", {"name": "dict_str", "type": "int"}, {"no_name": "here"}, ["list_str", "int"], [], 123]
  )
  assert res == ["simple_str", "dict_str", "list_str"]


def test_merge_tier_data_invalid_input():
  data = {}
  # Not a dictionary, should return early
  merge_tier_data(data, {}, {}, [], SemanticTier.EXTRAS)
  assert data == {}


def test_merge_tier_data_basic():
  data = {}
  origins = {}
  fws = {}
  patterns = []

  new_content = {
    "__frameworks__": {"tf": {"traits": {}}},
    "__patterns__": [{"name": "P1", "sequence": ["a"], "replace_with": "b"}],
    "Op1": {"description": "desc", "std_args": ["x"]},
  }

  merge_tier_data(data, origins, fws, new_content, SemanticTier.NEURAL, patterns)

  assert "tf" in fws
  assert len(patterns) == 1
  assert "Op1" in data
  assert origins["Op1"] == SemanticTier.NEURAL.value
  assert data["Op1"]["std_args"] == ["x"]


def test_merge_tier_data_validation_error(capsys):
  data = {}
  origins = {}

  # We cause validation error by making variants totally invalid
  # Actually 'operation' is injected if missing.
  # To cause validation error, we can put invalid type for std_args that pydantic rejects.
  new_content = {"OpError": {"std_args": "NOT_A_LIST"}}

  merge_tier_data(data, origins, {}, new_content, SemanticTier.NEURAL)
  assert "OpError" not in data
  captured = capsys.readouterr()
  assert "Skipping invalid definition" in captured.out


def test_merge_tier_data_idempotency():
  data = {
    "Op1": {"operation": "Op1", "description": "Autogenerated definition for Op1", "std_args": ["x"], "variants": {}}
  }
  origins = {"Op1": SemanticTier.NEURAL.value}

  new_content = {"Op1": {"std_args": ["x"]}}

  # Should skip because identical
  merge_tier_data(data, origins, {}, new_content, SemanticTier.NEURAL)
  assert len(data) == 1
  assert data["Op1"]["std_args"] == ["x"]


def test_merge_tier_data_downgrade_protection():
  data = {"Op1": {"operation": "Op1", "description": "orig", "std_args": ["x"], "variants": {}}}
  origins = {"Op1": SemanticTier.NEURAL.value}

  new_content = {"Op1": {"std_args": ["x", "y"]}}

  # Extras < Neural
  merge_tier_data(data, origins, {}, new_content, SemanticTier.EXTRAS)

  # Data is updated (because we always merge props), but origin is NOT updated
  assert data["Op1"]["std_args"] == ["x", "y"]
  assert origins["Op1"] == SemanticTier.NEURAL.value


def test_merge_tier_data_upgrade_silent():
  data = {"Op1": {"operation": "Op1", "description": "orig", "std_args": ["x"], "variants": {"fw1": {"foo": "bar"}}}}
  origins = {"Op1": SemanticTier.ARRAY_API.value}

  new_content = {"Op1": {"std_args": ["x", "y"], "variants": {"fw2": {"baz": "qux"}}}}

  # Neural > Array_API
  merge_tier_data(data, origins, {}, new_content, SemanticTier.NEURAL)

  # Origin updated
  assert origins["Op1"] == SemanticTier.NEURAL.value
  # Variants merged
  assert "fw1" in data["Op1"]["variants"]
  assert "fw2" in data["Op1"]["variants"]


def test_merge_tier_data_missing_injections():
  data = {}
  origins = {}

  # Missing description, std_args, operation, variants
  new_content = {"OpMissing": {}}

  merge_tier_data(data, origins, {}, new_content, SemanticTier.NEURAL, is_internal=True)

  assert "OpMissing" in data
  assert data["OpMissing"]["std_args"] == []
  assert data["OpMissing"]["description"] == "Autogenerated definition for OpMissing"
  assert data["OpMissing"]["_is_internal"] is True


def test_merge_tier_data_conflict_resolution_upgrade():
  data = {"Op1": {"operation": "Op1", "description": "old desc", "std_args": ["a", "b"], "variants": {}}}
  origins = {"Op1": SemanticTier.NEURAL.value}

  # New spec is richer (longer) -> Upgrade
  new_content_longer = {"Op1": {"std_args": ["a", "b", "c"]}}
  merge_tier_data(data, origins, {}, new_content_longer, SemanticTier.NEURAL)
  assert data["Op1"]["std_args"] == ["a", "b", "c"]


def test_merge_overlay_data_missing_variants():
  data = {"OpNoVariants": {"description": "desc"}}
  origins = {}

  content = {"__framework__": "torch", "mappings": {"OpNoVariants": {"mapped": True}}}

  merge_overlay_data(data, origins, {}, {}, content, "torch.json")
  assert "variants" in data["OpNoVariants"]
  assert data["OpNoVariants"]["variants"]["torch"] == {"mapped": True}


def test_merge_tier_data_conflict_resolution():
  data = {"Op1": {"operation": "Op1", "description": "old desc", "std_args": ["a", "b", "c"], "variants": {}}}
  origins = {"Op1": SemanticTier.NEURAL.value}

  # New spec is subset (shorter) -> Should preserve old details
  new_content_shorter = {"Op1": {"std_args": ["a", "b"]}}
  merge_tier_data(data, origins, {}, new_content_shorter, SemanticTier.NEURAL)
  assert data["Op1"]["std_args"] == ["a", "b", "c"]
  assert data["Op1"]["description"] == "old desc"

  # New spec is different but same length -> Warning
  new_content_ambig = {"Op1": {"std_args": ["x", "y", "z"]}}
  with pytest.warns(UserWarning, match="Conflict detected for 'Op1'"):
    merge_tier_data(data, origins, {}, new_content_ambig, SemanticTier.NEURAL)

  # Internal overwrite
  data["Op1"]["_is_internal"] = True
  new_content_internal = {"Op1": {"std_args": ["p", "q", "r"]}}
  with warnings.catch_warnings():
    warnings.simplefilter("error")
    # Should NOT warn because it was internal, now overwritten
    merge_tier_data(data, origins, {}, new_content_internal, SemanticTier.NEURAL)
    assert data["Op1"]["std_args"] == ["p", "q", "r"]


def test_merge_overlay_data_fallback_filename():
  data = {}
  origins = {}
  fws = {}
  tmps = {}

  content = {"mappings": {}}
  # Can't determine
  merge_overlay_data(data, origins, fws, tmps, content, "bad_name.json")
  assert not fws

  # Guessed from filename
  merge_overlay_data(data, origins, fws, tmps, content, "torch_v1.0.json")
  assert not fws  # No framework inside content, but didn't return early


def test_merge_overlay_data_full():
  data = {"OpExists": {"variants": {}}}
  origins = {"OpExists": SemanticTier.NEURAL.value}
  fws = {"torch": {"existing": True}}
  tmps = {}

  content = {
    "__framework__": "torch",
    "templates": {"t1": "v1"},
    "framework": {"new": False},
    "mappings": {
      "OpExists": {"mapped": True},
      "OpNewUpper": {"mapped": True},
      "opNewLower": {"mapped": True},
      "OpDisabled": None,
    },
  }

  merge_overlay_data(data, origins, fws, tmps, content, "torch_v1.0.json")

  assert tmps["torch"] == {"t1": "v1"}
  assert fws["torch"]["existing"] is True
  assert fws["torch"]["new"] is False

  assert "OpExists" in data
  assert data["OpExists"]["variants"]["torch"] == {"mapped": True}

  assert "OpNewUpper" in data
  assert origins["OpNewUpper"] == SemanticTier.NEURAL.value
  assert data["OpNewUpper"]["variants"]["torch"] == {"mapped": True}

  assert "opNewLower" in data
  assert origins["opNewLower"] == SemanticTier.EXTRAS.value
  assert data["opNewLower"]["variants"]["torch"] == {"mapped": True}

  assert "OpDisabled" in data
  assert data["OpDisabled"]["variants"]["torch"] is None


def test_merge_overlay_data_new_framework():
  data = {}
  origins = {}
  fws = {}
  tmps = {}

  content = {"__framework__": "jax", "framework": {"alias": {}}, "mappings": {"Op1": {"x": "y"}}}

  merge_overlay_data(data, origins, fws, tmps, content, "jax_v1.0.json")
  assert "jax" in fws


def test_merge_overlay_data_disabled_then_enabled():
  data = {"Op1": {"variants": {"torch": None}}}
  origins = {}

  content = {"__framework__": "torch", "mappings": {"Op1": {"now": "enabled"}}}

  merge_overlay_data(data, origins, {}, {}, content, "torch.json")
  assert data["Op1"]["variants"]["torch"] == {"now": "enabled"}
