import pytest
from ml_switcheroo.compiler.backends.extras import (
  HtmlBackend,
  TikzBackend,
  LatexBackend,
  MlirBackend,
  StableHloBackend,
)
from ml_switcheroo.compiler.ir import LogicalGraph, LogicalNode, LogicalEdge


def test_html_backend_format_args():
  backend = HtmlBackend()
  meta = {"arg_0": "x", "kernel_size": "3", "arg_1": "y"}
  result = backend._format_args(meta)
  assert result == "x, kernel_size=3, y"


def test_html_backend_is_stateful():
  backend = HtmlBackend()
  assert backend._is_stateful(LogicalNode("n1", "Input")) is False
  assert backend._is_stateful(LogicalNode("n2", "func_add")) is False
  assert backend._is_stateful(LogicalNode("func_n3", "Linear")) is False
  assert backend._is_stateful(LogicalNode("n4", "Linear")) is True
  assert backend._is_stateful(LogicalNode("n5", "linear")) is False
  # Empty kind
  assert backend._is_stateful(LogicalNode("n6", "")) is False


def test_html_backend_clean_kind():
  backend = HtmlBackend()
  assert backend._clean_kind("func_relu") == "Relu"
  assert backend._clean_kind("nn.Conv2d") == "Conv2d"
  assert backend._clean_kind("linear") == "Linear"


def test_html_backend_create_arrow():
  backend = HtmlBackend()
  arrow_def = backend._create_arrow(0, 0, "def")
  assert arrow_def.style_class == "s-red"

  arrow_data = backend._create_arrow(0, 0, "data")
  assert arrow_data.style_class == "s-green"

  arrow_seq = backend._create_arrow(2, 4, "seq")
  assert arrow_seq.style_class == "s-blue"
  # y2 = 50 + (2 - 1) * 120 = 170
  assert arrow_seq.y2 == 170

  arrow_unk = backend._create_arrow(0, 0, "unknown")
  assert arrow_unk.style_class == ""


def test_html_backend_compile():
  backend = HtmlBackend()
  g = LogicalGraph("TestNet")

  # Add an empty graph test
  assert "TestNet" in backend.compile(g)

  g.nodes = [
    LogicalNode("in1", "Input"),
    LogicalNode("conv1", "Conv2d", {"arg_0": "x"}),
    LogicalNode("relu1", "func_relu", {"arg_0": "x"}),
    LogicalNode("out1", "Output"),
  ]
  g.edges = [LogicalEdge("in1", "conv1"), LogicalEdge("conv1", "relu1"), LogicalEdge("relu1", "out1")]

  html = backend.compile(g)
  assert "TestNet" in html
  assert "Conv2d" in html
  assert "Relu" in html


def test_html_backend_compile_no_name():
  backend = HtmlBackend()
  g = LogicalGraph()
  g.nodes = [LogicalNode("conv1", "Conv2d")]
  html = backend.compile(g)
  assert "Model" in html


def test_tikz_backend_compile():
  backend = TikzBackend()
  g = LogicalGraph("TestNet")

  # Empty
  assert "Generated by ml-switcheroo" in backend.compile(g)

  g.nodes = [
    LogicalNode("in_1", "Input"),
    LogicalNode("conv_1", "nn.Conv2d", {"in_channels": "3"}),
    LogicalNode("out_1", "Output"),
  ]
  g.edges = [LogicalEdge("in_1", "conv_1"), LogicalEdge("conv_1", "out_1")]

  tikz = backend.compile(g)
  assert "Generated by ml-switcheroo" in tikz
  assert "in\\_1" in tikz
  assert "conv\\_1" in tikz
  assert "nn.Conv2d" in tikz
  assert "in\\_channels: 3" in tikz


def test_tikz_backend_disconnected_components():
  backend = TikzBackend()
  g = LogicalGraph()
  g.nodes = [LogicalNode("a", "OpA"), LogicalNode("b", "OpB")]
  # No edges
  tikz = backend.compile(g)
  assert "OpA" in tikz
  assert "OpB" in tikz


def test_tikz_backend_queue_logic():
  backend = TikzBackend()
  g = LogicalGraph()
  # Create graph with cycle or without degree 0 to test else branches
  g.nodes = [LogicalNode("a", "OpA"), LogicalNode("b", "OpB")]
  g.edges = [LogicalEdge("a", "b"), LogicalEdge("b", "a")]

  tikz = backend.compile(g)
  assert "OpA" in tikz


def test_latex_backend_compile():
  backend = LatexBackend()
  g = LogicalGraph("TestNet")

  # Empty
  latex = backend.compile(g)
  assert "\\documentclass" in latex
  assert "TestNet" in latex

  g.nodes = [
    LogicalNode("in", "Input"),
    LogicalNode("conv", "Conv2d", {"arg_0": "x"}),
    LogicalNode("relu", "func_relu", {"arg_0": "x"}),
    LogicalNode("out", "Output"),
  ]
  g.edges = [LogicalEdge("in", "conv"), LogicalEdge("conv", "relu"), LogicalEdge("relu", "out")]
  latex = backend.compile(g)
  assert "\\documentclass" in latex
  assert "TestNet" in latex
  assert "Conv2d" in latex
  assert "relu" in latex


def test_latex_backend_compile_no_name():
  backend = LatexBackend()
  g = LogicalGraph()
  g.nodes = [LogicalNode("in", "Input")]
  latex = backend.compile(g)
  assert "Model" in latex


def test_latex_backend_transcode_graph_no_input_output():
  backend = LatexBackend()
  g = LogicalGraph()
  g.nodes = [LogicalNode("a", "OpA"), LogicalNode("b", "OpB")]
  g.edges = [LogicalEdge("a", "b")]
  latex = backend.compile(g)
  assert "OpA" in latex
  assert "OpB" in latex


def test_latex_backend_transcode_graph_func_memory():
  backend = LatexBackend()
  g = LogicalGraph()
  g.nodes = [LogicalNode("func_a", "OpA"), LogicalNode("a", "OpA")]
  g.edges = [LogicalEdge("func_a", "a"), LogicalEdge("a", "output")]
  latex = backend.compile(g)
  assert "OpA" in latex


def test_mlir_backend_compile():
  backend = MlirBackend()
  g = LogicalGraph()
  g.nodes = [
    LogicalNode("in", "Input", {"value": "42"}),
    LogicalNode("in2", "Input", {"value": "float"}),
    LogicalNode("op", "MyOp", {"attr": "v"}),
    LogicalNode("op_no_attr", "MyOp", {}),
    LogicalNode("out", "Output"),
  ]
  mlir = backend.compile(g)
  assert "value = 42" in mlir
  assert 'type = "Input"' in mlir
  assert 'type = "MyOp", attr = "v"' in mlir
  assert 'type = "MyOp"' in mlir
  assert '"sw.return"()' in mlir


def test_stablehlo_backend_compile():
  backend = StableHloBackend()
  g = LogicalGraph()
  g.nodes = [LogicalNode("in", "Input"), LogicalNode("op", "math.Add"), LogicalNode("out", "Output")]
  shlo = backend.compile(g)
  assert "stablehlo.constant dense<0.0>" in shlo
  assert "stablehlo.custom_call @add" in shlo
  assert "return" in shlo


def test_latex_dsl_backend_unranked_node():
  from ml_switcheroo.compiler.backends.extras import TikzBackend as LatexBackend
  from ml_switcheroo.core.graph import LogicalGraph, LogicalNode, LogicalEdge
  from ml_switcheroo.semantics.manager import SemanticsManager

  backend = LatexBackend(SemanticsManager())
  # Node not connected to input so it doesn't get ranked in BFS
  graph = LogicalGraph(
    nodes=[LogicalNode("in", "Input"), LogicalNode("a", "Conv2d"), LogicalNode("b", "Conv2d")],
    edges=[LogicalEdge("a", "b"), LogicalEdge("b", "a")],
  )
  # line 453-454: max_rank += 1; ranks[n.id] = max_rank
  code = backend.compile(graph)
  assert "Conv2d" in code


def test_latex_backend_visited_ops():
  from ml_switcheroo.compiler.backends.extras import LatexBackend
  from ml_switcheroo.core.graph import LogicalGraph, LogicalNode, LogicalEdge
  from ml_switcheroo.semantics.manager import SemanticsManager

  backend = LatexBackend(SemanticsManager())
  graph = LogicalGraph(
    nodes=[LogicalNode("i1", "Input"), LogicalNode("i2", "Input"), LogicalNode("op", "add")],
    edges=[LogicalEdge("i1", "op"), LogicalEdge("i2", "op")],
  )
  code = backend.compile(graph)

  graph2 = LogicalGraph(
    nodes=[
      LogicalNode("in", "Input"),
      LogicalNode("func_add_id", "func_add", {"arg_2": "val", "kw": "2"}),
      LogicalNode("func_dot", "torch.add", {}),
    ],
    edges=[LogicalEdge("in", "func_add_id"), LogicalEdge("func_add_id", "func_dot")],
  )
  code2 = backend.compile(graph2)
  assert "func_add" not in code2.replace("func_add_id", "replaced")
  assert "Add" in code2

  # Test HtmlBackend for dot handling
  from ml_switcheroo.compiler.backends.extras import HtmlBackend

  backend3 = HtmlBackend(SemanticsManager())
  code3 = backend3.compile(graph2)
  assert "Add" in code3


def test_html_backend_visited_ops():
  from ml_switcheroo.compiler.backends.extras import HtmlBackend
  from ml_switcheroo.core.graph import LogicalGraph, LogicalNode, LogicalEdge
  from ml_switcheroo.semantics.manager import SemanticsManager

  backend = HtmlBackend(SemanticsManager())
  # line 647: target_id in visited_ops
  # Force two edges to same target so it's visited twice
  graph = LogicalGraph(
    nodes=[LogicalNode("i1", "Input"), LogicalNode("i2", "Input"), LogicalNode("op", "add")],
    edges=[LogicalEdge("i1", "op"), LogicalEdge("i2", "op")],
  )
  code = backend.compile(graph)
  assert "add" in code

  # 660-674: metadata handling, func_ prefix, etc.
  graph2 = LogicalGraph(
    nodes=[
      LogicalNode("in", "Input"),
      LogicalNode("func_add_id", "func_add", {"arg_2": "val", "kw": "2"}),
      LogicalNode("func_dot", "torch.add", {}),
    ],
    edges=[LogicalEdge("in", "func_add_id"), LogicalEdge("func_add_id", "func_dot")],
  )
  code2 = backend.compile(graph2)
  assert "func_add" not in code2.replace("func_add_id", "replaced")
  assert "Add" in code2

  # Test HtmlBackend for dot handling
  from ml_switcheroo.compiler.backends.extras import HtmlBackend

  backend3 = HtmlBackend(SemanticsManager())
  code3 = backend3.compile(graph2)
  assert "Add" in code3  # should be "Add"
  assert "val" in code2
  assert "kw=2" in code2
