"""Test suite for the Extras Gap module."""

from ml_switcheroo.core.compiler.backends.html import HtmlBackend
from ml_switcheroo.core.compiler.backends.mlir_backend import MlirBackend
from ml_switcheroo.core.compiler.backends.stablehlo import StableHloBackend
from ml_switcheroo.core.compiler.backends.visual_tikz import TikzBackend
from ml_switcheroo.core.compiler.backends.visual_latex import LatexBackend
from ml_switcheroo.core.compiler.ir import LogicalGraph, LogicalNode, LogicalEdge


def test_html_backend_format_args():
  """Verifies the behavior of HTML backend format arguments."""
  backend = HtmlBackend()
  meta = {"arg_0": "x", "kernel_size": "3", "arg_1": "y"}
  result = backend._format_args(meta)
  assert result == "x, kernel_size=3, y"


def test_html_backend_is_stateful():
  """Verifies the behavior of HTML backend is stateful."""
  backend = HtmlBackend()
  assert backend._is_stateful(LogicalNode("n1", "Input")) is False
  assert backend._is_stateful(LogicalNode("n2", "func_add")) is False
  assert backend._is_stateful(LogicalNode("func_n3", "Linear")) is False
  assert backend._is_stateful(LogicalNode("n4", "Linear")) is True
  assert backend._is_stateful(LogicalNode("n5", "linear")) is False
  assert backend._is_stateful(LogicalNode("n6", "")) is False


def test_html_backend_clean_kind():
  """Verifies the behavior of HTML backend clean kind."""
  backend = HtmlBackend()
  assert backend._clean_kind("func_relu") == "Relu"
  assert backend._clean_kind("nn.Conv2d") == "Conv2d"
  assert backend._clean_kind("linear") == "Linear"


def test_html_backend_create_arrow():
  """Verifies the behavior of HTML backend create arrow."""
  backend = HtmlBackend()
  arrow_def = backend._create_arrow(0, 0, "def")
  assert arrow_def.style_class == "s-red"
  arrow_data = backend._create_arrow(0, 0, "data")
  assert arrow_data.style_class == "s-green"
  arrow_seq = backend._create_arrow(2, 4, "seq")
  assert arrow_seq.style_class == "s-blue"
  assert arrow_seq.y2 == 170
  arrow_unk = backend._create_arrow(0, 0, "unknown")
  assert arrow_unk.style_class == ""


def test_html_backend_compile():
  """Verifies the behavior of HTML backend compile."""
  backend = HtmlBackend()
  g = LogicalGraph("TestNet")
  assert "TestNet" in backend.compile(g)
  g.nodes = [
    LogicalNode("in1", "Input"),
    LogicalNode("conv1", "Conv2d", {"arg_0": "x"}),
    LogicalNode("relu1", "func_relu", {"arg_0": "x"}),
    LogicalNode("out1", "Output"),
  ]
  g.edges = [LogicalEdge("in1", "conv1"), LogicalEdge("conv1", "relu1"), LogicalEdge("relu1", "out1")]
  html = backend.compile(g)
  assert "TestNet" in html
  assert "Conv2d" in html
  assert "Relu" in html


def test_html_backend_compile_no_name():
  """Verifies the behavior of HTML backend compile no name."""
  backend = HtmlBackend()
  g = LogicalGraph()
  g.nodes = [LogicalNode("conv1", "Conv2d")]
  html = backend.compile(g)
  assert "Model" in html


def test_tikz_backend_compile():
  """Verifies the behavior of TikZ backend compile."""
  backend = TikzBackend()
  g = LogicalGraph("TestNet")
  assert "Generated by ml-switcheroo" in backend.compile(g)
  g.nodes = [
    LogicalNode("in_1", "Input"),
    LogicalNode("conv_1", "nn.Conv2d", {"in_channels": "3"}),
    LogicalNode("out_1", "Output"),
  ]
  g.edges = [LogicalEdge("in_1", "conv_1"), LogicalEdge("conv_1", "out_1")]
  tikz = backend.compile(g)
  assert "Generated by ml-switcheroo" in tikz
  assert "in\\_1" in tikz
  assert "conv\\_1" in tikz
  assert "nn.Conv2d" in tikz
  assert "in\\_channels: 3" in tikz


def test_tikz_backend_disconnected_components():
  """Verifies the behavior of TikZ backend disconnected components."""
  backend = TikzBackend()
  g = LogicalGraph()
  g.nodes = [LogicalNode("a", "OpA"), LogicalNode("b", "OpB")]
  tikz = backend.compile(g)
  assert "OpA" in tikz
  assert "OpB" in tikz


def test_tikz_backend_queue_logic():
  """Verifies the behavior of TikZ backend queue logic."""
  backend = TikzBackend()
  g = LogicalGraph()
  g.nodes = [LogicalNode("a", "OpA"), LogicalNode("b", "OpB")]
  g.edges = [LogicalEdge("a", "b"), LogicalEdge("b", "a")]
  tikz = backend.compile(g)
  assert "OpA" in tikz


def test_latex_backend_compile():
  """Verifies the behavior of LaTeX backend compile."""
  backend = LatexBackend()
  g = LogicalGraph("TestNet")
  latex = backend.compile(g)
  assert "\\documentclass" in latex
  assert "TestNet" in latex
  g.nodes = [
    LogicalNode("in", "Input"),
    LogicalNode("conv", "Conv2d", {"arg_0": "x"}),
    LogicalNode("relu", "func_relu", {"arg_0": "x"}),
    LogicalNode("out", "Output"),
  ]
  g.edges = [LogicalEdge("in", "conv"), LogicalEdge("conv", "relu"), LogicalEdge("relu", "out")]
  latex = backend.compile(g)
  assert "\\documentclass" in latex
  assert "TestNet" in latex
  assert "Conv2d" in latex
  assert "relu" in latex


def test_latex_backend_compile_no_name():
  """Verifies the behavior of LaTeX backend compile no name."""
  backend = LatexBackend()
  g = LogicalGraph()
  g.nodes = [LogicalNode("in", "Input")]
  latex = backend.compile(g)
  assert "Model" in latex


def test_latex_backend_transcode_graph_no_input_output():
  """Verifies the behavior of LaTeX backend transcode graph no input output."""
  backend = LatexBackend()
  g = LogicalGraph()
  g.nodes = [LogicalNode("a", "OpA"), LogicalNode("b", "OpB")]
  g.edges = [LogicalEdge("a", "b")]
  latex = backend.compile(g)
  assert "OpA" in latex
  assert "OpB" in latex


def test_latex_backend_transcode_graph_func_memory():
  """Verifies the behavior of LaTeX backend transcode graph function memory."""
  backend = LatexBackend()
  g = LogicalGraph()
  g.nodes = [LogicalNode("func_a", "OpA"), LogicalNode("a", "OpA")]
  g.edges = [LogicalEdge("func_a", "a"), LogicalEdge("a", "output")]
  latex = backend.compile(g)
  assert "OpA" in latex

  def test_mlir_backend_compile():
    """Verifies the behavior of MLIR backend compile."""
    backend = MlirBackend()
    g = LogicalGraph()
    g.nodes = [
      LogicalNode("in", "Input", {"value": "42"}),
      LogicalNode("in2", "Input", {"value": "float"}),
      LogicalNode("op", "MyOp", {"attr": "v"}),
      LogicalNode("op_no_attr", "MyOp", {}),
      LogicalNode("out", "Output"),
    ]
    mlir = backend.compile(g)
    assert "value = 42" in mlir
    assert 'type = "Input"' in mlir
    assert 'type = "MyOp", attr = "v"' in mlir
    assert 'type = "MyOp"' in mlir
    assert '"sw.return" : ()' in mlir


def test_stablehlo_backend_compile():
  """Verifies the behavior of StableHLO backend compile."""
  backend = StableHloBackend()
  g = LogicalGraph()
  g.nodes = [LogicalNode("in", "Input"), LogicalNode("op", "math.Add"), LogicalNode("out", "Output")]
  shlo = backend.compile(g)
  assert "stablehlo.constant" in shlo
  assert "dense<0.0>" in shlo
  assert "stablehlo.custom_call" in shlo
  assert "@add" in shlo
  assert "return" in shlo


def test_latex_dsl_backend_unranked_node():
  """Verifies the behavior of LaTeX DSL backend unranked node."""
  from ml_switcheroo.core.compiler.backends import TikzBackend as LatexBackend
  from ml_switcheroo.core.graph import LogicalGraph, LogicalNode, LogicalEdge
  from ml_switcheroo.semantics.manager import SemanticsManager

  backend = LatexBackend(SemanticsManager())
  graph = LogicalGraph(
    nodes=[LogicalNode("in", "Input"), LogicalNode("a", "Conv2d"), LogicalNode("b", "Conv2d")],
    edges=[LogicalEdge("a", "b"), LogicalEdge("b", "a")],
  )
  code = backend.compile(graph)
  assert "Conv2d" in code


def test_latex_backend_visited_ops():
  """Verifies the behavior of LaTeX backend visited ops."""
  from ml_switcheroo.core.compiler.backends import LatexBackend
  from ml_switcheroo.core.graph import LogicalGraph, LogicalNode, LogicalEdge
  from ml_switcheroo.semantics.manager import SemanticsManager

  backend = LatexBackend(SemanticsManager())
  graph = LogicalGraph(
    nodes=[LogicalNode("i1", "Input"), LogicalNode("i2", "Input"), LogicalNode("op", "add")],
    edges=[LogicalEdge("i1", "op"), LogicalEdge("i2", "op")],
  )
  backend.compile(graph)
  graph2 = LogicalGraph(
    nodes=[
      LogicalNode("in", "Input"),
      LogicalNode("func_add_id", "func_add", {"arg_2": "val", "kw": "2"}),
      LogicalNode("func_dot", "torch.add", {}),
    ],
    edges=[LogicalEdge("in", "func_add_id"), LogicalEdge("func_add_id", "func_dot")],
  )
  code2 = backend.compile(graph2)
  assert "func_add" not in code2.replace("func_add_id", "replaced")
  assert "Add" in code2
  from ml_switcheroo.core.compiler.backends import HtmlBackend

  backend3 = HtmlBackend(SemanticsManager())
  code3 = backend3.compile(graph2)
  assert "Add" in code3


def test_html_backend_visited_ops():
  """Verifies the behavior of HTML backend visited ops."""
  from ml_switcheroo.core.compiler.backends import HtmlBackend
  from ml_switcheroo.core.graph import LogicalGraph, LogicalNode, LogicalEdge
  from ml_switcheroo.semantics.manager import SemanticsManager

  backend = HtmlBackend(SemanticsManager())
  graph = LogicalGraph(
    nodes=[LogicalNode("i1", "Input"), LogicalNode("i2", "Input"), LogicalNode("op", "add")],
    edges=[LogicalEdge("i1", "op"), LogicalEdge("i2", "op")],
  )
  code = backend.compile(graph)
  assert "add" in code
  graph2 = LogicalGraph(
    nodes=[
      LogicalNode("in", "Input"),
      LogicalNode("func_add_id", "func_add", {"arg_2": "val", "kw": "2"}),
      LogicalNode("func_dot", "torch.add", {}),
    ],
    edges=[LogicalEdge("in", "func_add_id"), LogicalEdge("func_add_id", "func_dot")],
  )
  code2 = backend.compile(graph2)
  assert "func_add" not in code2.replace("func_add_id", "replaced")
  assert "Add" in code2
  from ml_switcheroo.core.compiler.backends import HtmlBackend

  backend3 = HtmlBackend(SemanticsManager())
  code3 = backend3.compile(graph2)
  assert "Add" in code3
  assert "val" in code2
  assert "kw=2" in code2
