"""SASS SassInstruction Analyzer.

This module implements heuristics to extract high-level semantic parameters
(like Loop Bounds, Kernel Sizes, etc.) by analyzing the raw SASS instructions
AST generated by the parser.
"""

from typing import Any, Dict, List

from ml_switcheroo.core.compiler.frontends.sass.cst import SassImmediate, SassInstruction


class SassAnalyzer:
  """Analyzes sequences of SASS instructions to reverse-engineer high-level parameters."""

  @staticmethod
  def analyze_block(kind: str, instructions: List["SassInstruction"]) -> Dict[str, Any]:
    """Extracts metadata from a block of instructions based on the operation kind.

    Args:
        kind (str): The operation type (e.g. "Conv2d", "Linear").
        instructions (list): The assembly lines inside the block.

    Returns:
        Dict[str, Any]: Extracted parameters (e.g., {"kernel_size": 3}).

    """
    metadata = {}  # type: ignore

    # Heuristic 1: Loop Bounds
    # Look for ISETP.LT.AND (Integer Set SassPredicate Less-Than)
    # Usage: ISETP.LT.AND P0, PT, Reg, SassImmediate, PT;
    loop_limits = []
    for inst in instructions:
      if inst.opcode == "ISETP.LT.AND":
        for op in inst.operands:
          if isinstance(op, SassImmediate):
            loop_limits.append(op.value)

    if not loop_limits:
      return metadata

    if kind == "Conv2d":
      # Conv2d usually has 2 spatial loops (Ky, Kx).
      # We take the max found limit as the kernel_size estimate.
      k_size = max(loop_limits)
      metadata["kernel_size"] = k_size
      metadata["arg_2"] = k_size

    elif kind == "Linear":
      # Linear usually has 1 inner dot-product loop over input features.
      if loop_limits:
        feat_dim = max(loop_limits)
        metadata["in_features"] = feat_dim
        metadata["arg_0"] = feat_dim

    elif kind == "Conv3d":
      k_size = max(loop_limits)
      metadata["kernel_size"] = k_size
      metadata["arg_2"] = k_size

    elif kind in ("AvgPool2d", "MaxPool2d"):
      k_size = max(loop_limits)
      metadata["kernel_size"] = k_size
      metadata["arg_2"] = k_size

    elif kind == "BatchNorm2d":
      pass

    elif kind in ("Conv1d", "DepthwiseConv2d", "ConvTranspose1d", "ConvTranspose2d", "ConvTranspose3d"):
      pass

    elif kind in ("BatchNorm1d", "BatchNorm3d", "LayerNorm", "GroupNorm", "InstanceNorm2d"):
      pass

    elif kind in ("Softmax", "LogSoftmax", "SiLU", "Swish", "ELU", "LeakyReLU"):
      pass

    elif kind in ("BMM", "Dot", "SVD", "Solve", "Cholesky"):
      pass

    elif kind in ("Sum", "Prod", "Min", "Max", "ArgMax", "ArgMin", "Any", "All"):
      pass

    elif kind in ("BCEWithLogitsLoss", "L1Loss", "NLLLoss"):
      pass

    elif kind in ("Dropout2d", "Dropout3d", "AlphaDropout"):
      pass

    elif kind in ("AvgPool1d", "MaxPool1d", "AvgPool3d", "MaxPool3d", "AdaptiveAvgPool2d", "AdaptiveMaxPool2d"):
      pass

    elif kind in ("MultiheadAttention", "Transformer", "TransformerEncoder", "TransformerDecoder"):
      pass

    elif kind in ("RNN", "LSTM", "GRU", "LSTMCell", "GRUCell"):
      pass

    elif kind in ("MSELoss", "CrossEntropyLoss"):
      elems = max(loop_limits)
      metadata["elements"] = elems
      metadata["arg_0"] = elems

    elif kind in ("Sigmoid", "Tanh", "GELU"):
      pass

    elif kind in ("Dropout", "MatMul"):
      pass

    elif kind == "Mean":
      elems = max(loop_limits)
      metadata["elements"] = elems
      metadata["arg_0"] = elems

    return metadata
