description: Applies a series of layers to an input.
op_type: class
std_args:
- is_variadic: false
  kind: positional_or_keyword
  name: layers
  type: List
variants:
  keras:
    api: keras.layers.Pipeline
    args:
      layers: layers
      name: name
    dispatch_rules: []
    pack_as: Tuple
    required_imports: []
  sklearn:
    api: sklearn.pipeline.Pipeline
    args: {}
  huggingface:
    api: transformers.Pipeline
    args: {}
  tensorflow:
    api: tf.keras.layers.Pipeline
    dispatch_rules: []
    pack_as: Tuple
    required_imports: []
  paxml:
    api: praxis.layers.Sequential
    dispatch_rules: []
    pack_as: Tuple
    required_imports: []
  mlx:
    api: mlx.nn.Sequential
    dispatch_rules: []
    pack_as: Tuple
    required_imports: []
  torch:
    api: torch.nn.Sequential
    dispatch_rules: []
    pack_as: Tuple
    pack_to_tuple: args
    required_imports: []
  flax_nnx:
    api: flax.nnx.Sequential
    dispatch_rules: []
    pack_as: Tuple
    required_imports: []
operation: Pipeline
type: function
