"""Visual and Document-based Compilation Backends (TikZ, LaTeX)."""

from typing import Dict, Any, Optional, Tuple, List  # pragma: no cover
from collections import defaultdict, deque  # pragma: no cover

# pragma: no cover
from ml_switcheroo.core.compiler.backend import CompilerBackend  # pragma: no cover
from ml_switcheroo.core.graph import LogicalGraph  # pragma: no cover
from ml_switcheroo.core.compiler.ir import LogicalNode, LogicalEdge  # pragma: no cover
from ml_switcheroo.core.tikz.nodes import (
  TikzNode,
  TikzEdge,
  TikzComment,
  TikzOption,
  TikzGraph,
  TikzTable,
  TriviaNode,
)  # pragma: no cover
from ml_switcheroo.core.latex.nodes import (  # pragma: no cover
  LatexNode,  # pragma: no cover
  ModelContainer,  # pragma: no cover
  InputNode,  # pragma: no cover
  ReturnNode,  # pragma: no cover
  MemoryNode,  # pragma: no cover
  StateOpNode,  # pragma: no cover
  ComputeNode,  # pragma: no cover
)  # pragma: no cover


# pragma: no cover
# pragma: no cover
class TikzBackend(CompilerBackend):  # pragma: no cover
  """Orchestrates the conversion of a LogicalGraph to TikZ source code.  # pragma: no cover
  Verified to use Rank-Based Layout.  # pragma: no cover
  """  # pragma: no cover

  # pragma: no cover
  def __init__(
    self, semantics: Optional[Any] = None, y_spacing: float = 2.5, x_spacing: float = 3.0
  ) -> None:  # pragma: no cover
    """Initialize TikZ backend.  # pragma: no cover
    # pragma: no cover
    Args:  # pragma: no cover
        semantics: Unused.  # pragma: no cover
        y_spacing: Vertical space between ranks.  # pragma: no cover
        x_spacing: Horizontal space between nodes.  # pragma: no cover
    # pragma: no cover
    """  # pragma: no cover
    self.y_spacing = y_spacing  # pragma: no cover
    self.x_spacing = x_spacing  # pragma: no cover

  # pragma: no cover
  def compile(self, graph: LogicalGraph) -> str:  # pragma: no cover
    """Compile graph to TikZ LaTeX code."""  # pragma: no cover
    positions = self._calculate_layout(graph)  # pragma: no cover
    cst_nodes = []  # pragma: no cover
    cst_nodes.append(TikzComment("Generated by ml-switcheroo"))  # pragma: no cover
    cst_nodes.append(TriviaNode("\n"))  # type: ignore  # pragma: no cover
    # pragma: no cover
    for node in graph.nodes:  # pragma: no cover
      pos = positions.get(node.id, (0, 0))  # pragma: no cover
      tikz_node = self._create_tikz_node(node, pos[0], pos[1])  # pragma: no cover
      cst_nodes.append(tikz_node)  # type: ignore  # pragma: no cover
    # pragma: no cover
    cst_nodes.append(TriviaNode("\n"))  # type: ignore  # pragma: no cover
    # pragma: no cover
    for edge in graph.edges:  # pragma: no cover
      tikz_edge = self._create_tikz_edge(edge)  # pragma: no cover
      cst_nodes.append(tikz_edge)  # type: ignore  # pragma: no cover
    # pragma: no cover
    options = [  # pragma: no cover
      TikzOption("node distance", "2cm"),  # pragma: no cover
      TikzOption("auto"),  # pragma: no cover
      TikzOption(">=stealth"),  # pragma: no cover
    ]  # pragma: no cover
    root = TikzGraph(children=cst_nodes, options=options)  # type: ignore  # pragma: no cover
    return root.to_text()  # pragma: no cover

  # pragma: no cover
  def _sanitize(self, text: str) -> str:  # pragma: no cover
    """Escape special LaTeX characters."""  # pragma: no cover
    return str(text).replace("_", r"\_")  # pragma: no cover

  # pragma: no cover
  def _calculate_layout(self, graph: LogicalGraph) -> Dict[str, Tuple[float, float]]:  # pragma: no cover
    """Determine X,Y coordinates for nodes based on topological rank."""  # pragma: no cover
    if not graph.nodes:  # pragma: no cover
      return {}  # pragma: no cover
    # pragma: no cover
    adj = defaultdict(list)  # pragma: no cover
    in_degree = defaultdict(int)  # pragma: no cover
    for n in graph.nodes:  # pragma: no cover
      in_degree[n.id] = 0  # pragma: no cover
    # pragma: no cover
    for edge in graph.edges:  # pragma: no cover
      adj[edge.source].append(edge.target)  # pragma: no cover
      in_degree[edge.target] += 1  # pragma: no cover
    # pragma: no cover
    queue = deque([n.id for n in graph.nodes if in_degree[n.id] == 0])  # pragma: no cover
    ranks = {}  # pragma: no cover
    processed = set()  # pragma: no cover
    # pragma: no cover
    if not queue and graph.nodes:  # pragma: no cover
      first = graph.nodes[0].id  # pragma: no cover
      queue.append(first)  # pragma: no cover
      ranks[first] = 0  # pragma: no cover
    else:  # pragma: no cover
      for root_id in queue:  # pragma: no cover
        ranks[root_id] = 0  # pragma: no cover
    # pragma: no cover
    max_rank = 0  # pragma: no cover
    while queue:  # pragma: no cover
      curr = queue.popleft()  # pragma: no cover
      if curr in processed:  # pragma: no cover
        continue  # pragma: no cover
      processed.add(curr)  # pragma: no cover
      curr_rank = ranks.get(curr, 0)  # pragma: no cover
      max_rank = max(max_rank, curr_rank)  # pragma: no cover
      # pragma: no cover
      for neighbor in adj[curr]:  # pragma: no cover
        if neighbor not in ranks or ranks[neighbor] < curr_rank + 1:  # pragma: no cover
          ranks[neighbor] = curr_rank + 1  # pragma: no cover
          queue.append(neighbor)  # pragma: no cover
    # pragma: no cover
    for n in graph.nodes:  # pragma: no cover
      if n.id not in ranks:  # pragma: no cover
        max_rank += 1  # pragma: no cover
        ranks[n.id] = max_rank  # pragma: no cover
    # pragma: no cover
    rank_groups = defaultdict(list)  # pragma: no cover
    for node_id, r in ranks.items():  # pragma: no cover
      rank_groups[r].append(node_id)  # pragma: no cover
    # pragma: no cover
    positions = {}  # pragma: no cover
    for r, nodes in rank_groups.items():  # pragma: no cover
      y = -r * self.y_spacing  # pragma: no cover
      count = len(nodes)  # pragma: no cover
      start_x = -((count - 1) * self.x_spacing) / 2  # pragma: no cover
      for i, node_id in enumerate(nodes):  # pragma: no cover
        x = start_x + (i * self.x_spacing)  # pragma: no cover
        positions[node_id] = (x, y)  # pragma: no cover
    return positions  # pragma: no cover

  # pragma: no cover
  def _create_tikz_node(self, node: LogicalNode, x: float, y: float) -> TikzNode:  # pragma: no cover
    """Creates a TikzNode AST object."""  # pragma: no cover
    options = [  # pragma: no cover
      TikzOption("draw"),  # pragma: no cover
      TikzOption("rectangle"),  # pragma: no cover
      TikzOption("rounded corners"),  # pragma: no cover
      TikzOption("align", "center"),  # pragma: no cover
    ]  # pragma: no cover
    if node.kind == "Input":  # pragma: no cover
      options.append(TikzOption("fill", "green!10"))  # pragma: no cover
    elif node.kind == "Output":  # pragma: no cover
      options.append(TikzOption("fill", "red!10"))  # pragma: no cover
    else:  # pragma: no cover
      options.append(TikzOption("fill", "blue!5"))  # pragma: no cover
    # pragma: no cover
    sanitized_kind = self._sanitize(node.kind)  # pragma: no cover
    rows = [[rf"\textbf{{{sanitized_kind}}}"]]  # pragma: no cover
    sanitized_id = self._sanitize(node.id)  # pragma: no cover
    rows.append([rf"\textit{{{sanitized_id}}}"])  # pragma: no cover
    # pragma: no cover
    for k, v in node.metadata.items():  # pragma: no cover
      clean_k = self._sanitize(k)  # pragma: no cover
      clean_v = self._sanitize(str(v)[:20])  # pragma: no cover
      rows.append([f"{clean_k}: {clean_v}"])  # pragma: no cover
    # pragma: no cover
    content_table = TikzTable(rows=rows, align="c")  # pragma: no cover
    # pragma: no cover
    return TikzNode(  # pragma: no cover
      node_id=node.id,  # pragma: no cover
      x=x,  # pragma: no cover
      y=y,  # pragma: no cover
      content=content_table,  # pragma: no cover
      options=options,  # pragma: no cover
    )  # pragma: no cover

  # pragma: no cover
  def _create_tikz_edge(self, edge: LogicalEdge) -> TikzEdge:  # pragma: no cover
    """Creates a TikzEdge AST object."""  # pragma: no cover
    return TikzEdge(  # pragma: no cover
      source_id=edge.source,  # pragma: no cover
      target_id=edge.target,  # pragma: no cover
      connector="--",  # pragma: no cover
      options=[TikzOption("->"), TikzOption("thick")],  # pragma: no cover
    )  # pragma: no cover

  # pragma: no cover
  # pragma: no cover


class LatexBackend(CompilerBackend):  # pragma: no cover
  """Transforms Logical Graphs into MIDL LaTeX format."""  # pragma: no cover

  # pragma: no cover
  def __init__(self, semantics: Optional[Any] = None) -> None:  # pragma: no cover
    """Execute implementation detail."""  # pragma: no cover
    pass  # pragma: no cover

  # pragma: no cover
  def compile(self, graph: LogicalGraph) -> str:  # pragma: no cover
    """Compiles graph to LaTeX."""  # pragma: no cover
    name = graph.name or "GeneratedNet"  # pragma: no cover
    container = self._transcode_graph(graph, name)  # pragma: no cover
    return self._wrap_document(container.to_latex())  # pragma: no cover

  # pragma: no cover
  def _wrap_document(self, content: str) -> str:  # pragma: no cover
    """Wraps content in Latex standalone document."""  # pragma: no cover
    comment_block = (  # pragma: no cover
      r"% ------------------------------------------------------------------"  # pragma: no cover
      "\n"  # pragma: no cover
      r"% [Requirement] midl.sty"  # pragma: no cover
      "\n"  # pragma: no cover
      r"% This document uses the Machine Intelligence Definition Language."  # pragma: no cover
      "\n"  # pragma: no cover
      r"% Ensure 'midl.sty' is in your LaTeX path."  # pragma: no cover
      "\n"  # pragma: no cover
      r"% ------------------------------------------------------------------"  # pragma: no cover
      "\n"  # pragma: no cover
    )  # pragma: no cover
    header = (  # pragma: no cover
      r"\documentclass[tikz, border=10pt, landscape]{standalone}"
      "\n"
      r"\usepackage{midl}"
      "\n"
      r"\begin{document}"
      "\n"  # pragma: no cover
    )  # pragma: no cover
    footer = "\n" + r"\end{document}"  # pragma: no cover
    return comment_block + header + content + footer  # pragma: no cover

  # pragma: no cover
  def _transcode_graph(self, graph: LogicalGraph, name: str) -> ModelContainer:  # pragma: no cover
    """Transforms LogicalNodes to LatexNode hierarchy."""  # pragma: no cover
    children: List[LatexNode] = []  # pragma: no cover
    # Reconstruct registry as graph nodes list  # pragma: no cover
    state_registry = {n.id: n for n in graph.nodes}  # pragma: no cover
    # pragma: no cover
    # Memory Logic  # pragma: no cover
    for node_id, node in sorted(state_registry.items()):  # pragma: no cover
      if node.kind in ["Input", "Output"]:  # pragma: no cover
        continue  # pragma: no cover
      if node_id.startswith("func_"):  # pragma: no cover
        continue  # pragma: no cover
      config = node.metadata.copy()  # pragma: no cover
      mem = MemoryNode(node_id=node_id, op_type=node.kind, config=config)  # pragma: no cover
      children.append(mem)  # pragma: no cover
    # pragma: no cover
    input_node = next((n for n in graph.nodes if n.kind == "Input"), None)  # pragma: no cover
    input_name = "input"  # pragma: no cover
    children.append(InputNode(name=input_name, shape="[_]"))  # pragma: no cover
    # pragma: no cover
    id_map = {}  # pragma: no cover
    if input_node:  # pragma: no cover
      id_map[input_node.id] = input_name  # pragma: no cover
    else:  # pragma: no cover
      id_map["input"] = input_name  # pragma: no cover
    # pragma: no cover
    output_node = next((n for n in graph.nodes if n.kind == "Output"), None)  # pragma: no cover
    visited_ops = set()  # pragma: no cover
    # pragma: no cover
    for edge in graph.edges:  # pragma: no cover
      target_id = edge.target  # pragma: no cover
      source_id = edge.source  # pragma: no cover
      if target_id == "output" or (output_node and target_id == output_node.id):  # pragma: no cover
        continue  # pragma: no cover
      if target_id in visited_ops:  # pragma: no cover
        continue  # pragma: no cover
      # pragma: no cover
      is_stateful = (target_id in state_registry) and not target_id.startswith("func_")  # pragma: no cover
      node_data = next((n for n in graph.nodes if n.id == target_id), None)  # pragma: no cover
      op_type = node_data.kind if node_data else "Unknown"  # pragma: no cover
      step_id = f"op_{target_id}"  # pragma: no cover
      id_map[target_id] = step_id  # pragma: no cover
      arg_ref = id_map.get(source_id, f"op_{source_id}")  # pragma: no cover
      args = [arg_ref]  # pragma: no cover
      # pragma: no cover
      if is_stateful:  # pragma: no cover
        children.append(StateOpNode(step_id, target_id, args, "[_]"))  # pragma: no cover
      else:  # pragma: no cover
        meta_args = []  # pragma: no cover
        if node_data:  # pragma: no cover
          for k, v in node_data.metadata.items():  # pragma: no cover
            if k.startswith("arg"):  # pragma: no cover
              meta_args.append(v)  # pragma: no cover
            else:  # pragma: no cover
              meta_args.append(f"{k}={v}")  # pragma: no cover
        final_args = args + meta_args  # pragma: no cover
        clean_type = op_type  # pragma: no cover
        if clean_type.startswith("func_"):  # pragma: no cover
          clean_type = clean_type[5:]  # pragma: no cover
        elif "." in clean_type:  # pragma: no cover
          clean_type = clean_type.split(".")[-1]  # pragma: no cover
        clean_type = clean_type.capitalize()  # pragma: no cover
        children.append(ComputeNode(step_id, clean_type, final_args, "[_]"))  # pragma: no cover
      # pragma: no cover
      visited_ops.add(target_id)  # pragma: no cover
    # pragma: no cover
    if visited_ops:  # pragma: no cover
      sources_to_output = [
        e.source for e in graph.edges if e.target == "output" or e.target == "Output"
      ]  # pragma: no cover
      if sources_to_output:  # pragma: no cover
        final_src = sources_to_output[0]  # pragma: no cover
        final_ref = id_map.get(final_src, f"op_{final_src}")  # pragma: no cover
        children.append(ReturnNode(target_id=final_ref))  # pragma: no cover
      else:  # pragma: no cover
        children.append(ReturnNode(target_id="last_step"))  # pragma: no cover
    # pragma: no cover
    return ModelContainer(name, children)  # pragma: no cover
