"""Visual and Document-based Compilation Backends (TikZ, LaTeX).

This module provides compiler backends for exporting `LogicalGraph` structures
into graphical representations using TikZ or document-based representations
using a customized Machine Intelligence Definition Language (MIDL) LaTeX format.
"""

from typing import Dict, Any, Optional, Tuple, List, Union
from collections import defaultdict, deque


from ml_switcheroo.core.compiler.backend import CompilerBackend
from ml_switcheroo.core.graph import LogicalGraph
from ml_switcheroo.core.compiler.ir import LogicalNode, LogicalEdge
from ml_switcheroo.core.tikz.nodes import (
  TikzBaseNode,
  TikzNode,
  TikzEdge,
  TikzOption,
  TikzGraph,
  TikzTable,
  TikzTextNode,
  TriviaNode,
)
from ml_switcheroo.core.latex.nodes import (
  LatexNode,
  ModelContainer,
  InputNode,
  ReturnNode,
  MemoryNode,
  StateOpNode,
  ComputeNode,
)


class TikzBackend(CompilerBackend):
  """Orchestrates the conversion of a LogicalGraph to TikZ source code.

  Verified to use Rank-Based Layout.
  """

  def __init__(self, semantics: Optional[Any] = None, y_spacing: float = 2.5, x_spacing: float = 3.0) -> None:
    """Initialize the TikZ backend.

    Args:
        semantics: Unused semantic mapping or configuration.
        y_spacing: Vertical space between ranks. Defaults to 2.5.
        x_spacing: Horizontal space between nodes. Defaults to 3.0.
    """
    self.y_spacing = y_spacing
    self.x_spacing = x_spacing

  def compile(self, graph: LogicalGraph) -> str:
    """Compile a LogicalGraph to TikZ LaTeX code.

    Args:
        graph: The logical graph structure to be compiled.

    Returns:
        The generated TikZ LaTeX source code string representing the graph.
    """
    positions = self._calculate_layout(graph)
    cst_nodes: List[TikzBaseNode] = []
    cst_nodes.append(
      TriviaNode(
        "% Generated by ml-switcheroo\n",
      )
    )
    cst_nodes.append(TriviaNode("\n"))

    for node in graph.nodes:
      pos = positions.get(node.id, (0, 0))
      tikz_node = self._create_tikz_node(node, pos[0], pos[1])
      cst_nodes.append(tikz_node)

    cst_nodes.append(TriviaNode("\n"))

    for edge in graph.edges:
      tikz_edge = self._create_tikz_edge(edge)
      cst_nodes.append(tikz_edge)

    options = [
      TikzOption("node distance", "2cm"),
      TikzOption("auto"),
      TikzOption(">=stealth"),
    ]
    root = TikzGraph(children=cst_nodes, options=options)
    return root.to_text()

  def _sanitize(self, text: str) -> str:
    """Escape special LaTeX characters in a given string.

    Args:
        text: The raw string to be sanitized.

    Returns:
        The sanitized string with special characters (such as '_') properly escaped.
    """
    return str(text).replace("_", r"\_")

  def _calculate_layout(self, graph: LogicalGraph) -> Dict[str, Tuple[float, float]]:
    """Determine X, Y coordinates for nodes based on topological rank.

    Computes a rank-based layout by performing a topological sort and grouping
    nodes into hierarchical levels (ranks) to optimize vertical and horizontal spacing.

    Args:
        graph: The logical graph whose layout is to be calculated.

    Returns:
        A dictionary mapping node IDs to their computed (x, y) float coordinates.
    """
    if not graph.nodes:
      return {}

    adj = defaultdict(list)
    in_degree = defaultdict(int)
    for n in graph.nodes:
      in_degree[n.id] = 0

    for edge in graph.edges:
      adj[edge.source].append(edge.target)
      in_degree[edge.target] += 1

    queue = deque([n.id for n in graph.nodes if in_degree[n.id] == 0])
    ranks = {}
    processed = set()

    if not queue and graph.nodes:
      first = graph.nodes[0].id
      queue.append(first)
      ranks[first] = 0
    else:
      for root_id in queue:
        ranks[root_id] = 0

    max_rank = 0
    while queue:
      curr = queue.popleft()
      if curr in processed:
        continue
      processed.add(curr)
      curr_rank = ranks.get(curr, 0)
      max_rank = max(max_rank, curr_rank)

      for neighbor in adj[curr]:
        if neighbor not in ranks or ranks[neighbor] < curr_rank + 1:
          ranks[neighbor] = curr_rank + 1
          queue.append(neighbor)

    for n in graph.nodes:
      if n.id not in ranks:
        max_rank += 1
        ranks[n.id] = max_rank

    rank_groups = defaultdict(list)
    for node_id, r in ranks.items():
      rank_groups[r].append(node_id)

    positions = {}
    for r, nodes in rank_groups.items():
      y = -r * self.y_spacing
      count = len(nodes)
      start_x = -((count - 1) * self.x_spacing) / 2
      for i, node_id in enumerate(nodes):
        x = start_x + (i * self.x_spacing)
        positions[node_id] = (x, y)
    return positions

  def _create_tikz_node(self, node: LogicalNode, x: float, y: float) -> TikzNode:
    """Create a TikzNode AST object.

    Constructs a TikzNode with appropriate styles, styling options, positions,
    and structured table content representing the logical node and its metadata.

    Args:
        node: The LogicalNode representing the node in the graph.
        x: The computed X-coordinate for positioning the node.
        y: The computed Y-coordinate for positioning the node.

    Returns:
        A TikzNode AST object ready for serialization.
    """
    options = [
      TikzOption("draw"),
      TikzOption("rectangle"),
      TikzOption("rounded corners"),
      TikzOption("align", "center"),
    ]
    if node.kind == "Input":
      options.append(TikzOption("fill", "green!10"))
    elif node.kind == "Output":
      options.append(TikzOption("fill", "red!10"))
    else:
      options.append(TikzOption("fill", "blue!5"))

    sanitized_kind = self._sanitize(node.kind)
    rows: List[List[Union[str, TikzTextNode]]] = [[rf"\textbf{{{sanitized_kind}}}"]]
    sanitized_id = self._sanitize(node.id)
    rows.append([rf"\textit{{{sanitized_id}}}"])

    for k, v in node.metadata.items():
      clean_k = self._sanitize(k)
      clean_v = self._sanitize(str(v)[:20])
      rows.append([f"{clean_k}: {clean_v}"])

    content_table = TikzTable(rows=rows, align="c")

    return TikzNode(
      node_id=node.id,
      x=x,
      y=y,
      content=content_table,
      options=options,
    )

  def _create_tikz_edge(self, edge: LogicalEdge) -> TikzEdge:
    """Create a TikzEdge AST object.

    Args:
        edge: LogicalEdge to convert.

    Returns:
        The constructed TikzEdge object.
    """
    return TikzEdge(
      source_id=edge.source,
      target_id=edge.target,
      connector="--",
      options=[TikzOption("->"), TikzOption("thick")],
    )


class LatexBackend(CompilerBackend):
  """Transforms Logical Graphs into MIDL LaTeX format.

  Generates structured Machine Intelligence Definition Language (MIDL) LaTeX documents
  from a logical graph.
  """

  def __init__(self, semantics: Optional[Any] = None) -> None:
    """Initialize the LaTeX backend.

    Args:
        semantics: Unused semantic mapping or configuration.
    """
    pass

  def compile(self, graph: LogicalGraph) -> str:
    """Compile a LogicalGraph to a complete LaTeX document.

    Args:
        graph: The logical graph to compile.

    Returns:
        A string containing the full, standalone LaTeX document using the midl package.
    """
    name = graph.name or "GeneratedNet"
    container = self._transcode_graph(graph, name)
    return self._wrap_document(container.to_latex())

  def _wrap_document(self, content: str) -> str:
    """Wrap raw LaTeX content into a standalone document structure.

    Args:
        content: The raw LaTeX content body representing the model.

    Returns:
        The complete standalone LaTeX document string including package imports and setup.
    """
    comment_block = (
      r"% ------------------------------------------------------------------"
      "\n"
      r"% [Requirement] midl.sty"
      "\n"
      r"% This document uses the Machine Intelligence Definition Language."
      "\n"
      r"% Ensure 'midl.sty' is in your LaTeX path."
      "\n"
      r"% ------------------------------------------------------------------"
      "\n"
    )
    header = (
      r"\documentclass[tikz, border=10pt, landscape]{standalone}" "\n" r"\usepackage{midl}" "\n" r"\begin{document}" "\n"
    )
    footer = "\n" + r"\end{document}"
    return comment_block + header + content + footer

  def _transcode_graph(self, graph: LogicalGraph, name: str) -> ModelContainer:
    """Transform LogicalNode and LogicalEdge objects into a LatexNode hierarchy.

    Processes graph nodes and edges to construct structured LaTeX memory nodes,
    input/output blocks, and compute/state operations under a single model container.

    Args:
        graph: The logical graph to transcode.
        name: The name of the resulting model container.

    Returns:
        A ModelContainer node representing the root of the LaTeX AST.
    """
    children: List[LatexNode] = []
    # Reconstruct registry as graph nodes list
    state_registry = {n.id: n for n in graph.nodes}

    # RdnaMemory Logic
    for node_id, node in sorted(state_registry.items()):
      if node.kind in ["Input", "Output"]:
        continue
      if node_id.startswith("func_"):
        continue
      config = node.metadata.copy()
      mem = MemoryNode(node_id=node_id, op_type=node.kind, config=config)
      children.append(mem)

    input_node = next((n for n in graph.nodes if n.kind == "Input"), None)
    input_name = "input"
    children.append(InputNode(name=input_name, shape="[_]"))

    id_map = {}
    if input_node:
      id_map[input_node.id] = input_name
    else:
      id_map["input"] = input_name

    output_node = next((n for n in graph.nodes if n.kind == "Output"), None)
    visited_ops = set()

    for edge in graph.edges:
      target_id = edge.target
      source_id = edge.source
      if target_id == "output" or (output_node and target_id == output_node.id):
        continue
      if target_id in visited_ops:
        continue

      is_stateful = (target_id in state_registry) and not target_id.startswith("func_")
      node_data = next((n for n in graph.nodes if n.id == target_id), None)
      op_type = node_data.kind if node_data else "Unknown"
      step_id = f"op_{target_id}"
      id_map[target_id] = step_id
      arg_ref = id_map.get(source_id, f"op_{source_id}")
      args = [arg_ref]

      if is_stateful:
        children.append(StateOpNode(step_id, target_id, args, "[_]"))
      else:
        meta_args = []
        if node_data:
          for k, v in node_data.metadata.items():
            if k.startswith("arg"):
              meta_args.append(v)
            else:
              meta_args.append(f"{k}={v}")
        final_args = args + meta_args
        clean_type = op_type
        if clean_type.startswith("func_"):
          clean_type = clean_type[5:]
        elif "." in clean_type:
          clean_type = clean_type.split(".")[-1]
        clean_type = clean_type.capitalize()
        children.append(ComputeNode(step_id, clean_type, final_args, "[_]"))

      visited_ops.add(target_id)

    if visited_ops:
      sources_to_output = [e.source for e in graph.edges if e.target == "output" or e.target == "Output"]
      if sources_to_output:
        final_src = sources_to_output[0]
        final_ref = id_map.get(final_src, f"op_{final_src}")
        children.append(ReturnNode(target_id=final_ref))
      else:
        children.append(ReturnNode(target_id="last_step"))

    return ModelContainer(name, children)
