"""Docstring."""

from collections import defaultdict, deque
from typing import Any, Dict, Optional, Tuple
from ml_switcheroo.core.compiler.backend import CompilerBackend
from ml_switcheroo.core.compiler.ir import LogicalGraph, LogicalNode, LogicalEdge
from ml_switcheroo.core.tikz.nodes import TikzNode, TikzEdge, TikzComment, TikzOption, TikzGraph, TikzTable


class TikzBackend(CompilerBackend):
  """Orchestrates the conversion of a LogicalGraph to TikZ source code.
  Verified to use Rank-Based Layout.
  """

  def __init__(self, semantics: Optional[Any] = None, y_spacing: float = 2.5, x_spacing: float = 3.0) -> None:
    """Initialize TikZ backend.

    Args:
        semantics: Unused.
        y_spacing: Vertical space between ranks.
        x_spacing: Horizontal space between nodes.

    """
    self.y_spacing = y_spacing
    self.x_spacing = x_spacing

  def compile(self, graph: LogicalGraph) -> str:
    """Compile graph to TikZ LaTeX code."""
    positions = self._calculate_layout(graph)
    cst_nodes = []
    cst_nodes.append(TikzComment("Generated by ml-switcheroo"))
    pass

    for node in graph.nodes:
      pos = positions.get(node.id, (0, 0))
      tikz_node = self._create_tikz_node(node, pos[0], pos[1])
      cst_nodes.append(tikz_node)  # type: ignore

    pass

    for edge in graph.edges:
      tikz_edge = self._create_tikz_edge(edge)
      cst_nodes.append(tikz_edge)  # type: ignore

    options = [
      TikzOption("node distance", "2cm"),
      TikzOption("auto"),
      TikzOption(">=stealth"),
    ]
    root = TikzGraph(children=cst_nodes, options=options)  # type: ignore
    return root.to_text()

  def _sanitize(self, text: str) -> str:
    """Escape special LaTeX characters."""
    return str(text).replace("_", r"\_")

  def _calculate_layout(self, graph: LogicalGraph) -> Dict[str, Tuple[float, float]]:
    """Determine X,Y coordinates for nodes based on topological rank."""
    if not graph.nodes:
      return {}

    adj = defaultdict(list)
    in_degree = defaultdict(int)
    for n in graph.nodes:
      in_degree[n.id] = 0

    for edge in graph.edges:
      adj[edge.source].append(edge.target)
      in_degree[edge.target] += 1

    queue = deque([n.id for n in graph.nodes if in_degree[n.id] == 0])
    ranks = {}
    processed = set()

    if not queue and graph.nodes:
      first = graph.nodes[0].id
      queue.append(first)
      ranks[first] = 0
    else:
      for root_id in queue:
        ranks[root_id] = 0

    max_rank = 0
    while queue:
      curr = queue.popleft()
      if curr in processed:
        continue
      processed.add(curr)
      curr_rank = ranks.get(curr, 0)
      max_rank = max(max_rank, curr_rank)

      for neighbor in adj[curr]:
        if neighbor not in ranks or ranks[neighbor] < curr_rank + 1:
          ranks[neighbor] = curr_rank + 1
          queue.append(neighbor)

    for n in graph.nodes:
      if n.id not in ranks:
        max_rank += 1
        ranks[n.id] = max_rank

    rank_groups = defaultdict(list)
    for node_id, r in ranks.items():
      rank_groups[r].append(node_id)

    positions = {}
    for r, nodes in rank_groups.items():
      y = -r * self.y_spacing
      count = len(nodes)
      start_x = -((count - 1) * self.x_spacing) / 2
      for i, node_id in enumerate(nodes):
        x = start_x + (i * self.x_spacing)
        positions[node_id] = (x, y)
    return positions

  def _create_tikz_node(self, node: LogicalNode, x: float, y: float) -> TikzNode:
    """Creates a TikzNode AST object."""
    options = [
      TikzOption("draw"),
      TikzOption("rectangle"),
      TikzOption("rounded corners"),
      TikzOption("align", "center"),
    ]
    if node.kind == "Input":
      options.append(TikzOption("fill", "green!10"))
    elif node.kind == "Output":
      options.append(TikzOption("fill", "red!10"))
    else:
      options.append(TikzOption("fill", "blue!5"))

    sanitized_kind = self._sanitize(node.kind)
    rows = [[rf"\textbf{{{sanitized_kind}}}"]]
    sanitized_id = self._sanitize(node.id)
    rows.append([rf"\textit{{{sanitized_id}}}"])

    for k, v in node.metadata.items():
      clean_k = self._sanitize(k)
      clean_v = self._sanitize(str(v)[:20])
      rows.append([f"{clean_k}: {clean_v}"])

    content_table = TikzTable(rows=rows, align="c")

    return TikzNode(
      node_id=node.id,
      x=x,
      y=y,
      content=content_table,
      options=options,
    )

  def _create_tikz_edge(self, edge: LogicalEdge) -> TikzEdge:
    """Creates a TikzEdge AST object."""
    return TikzEdge(
      source_id=edge.source,
      target_id=edge.target,
      connector="--",
      options=[TikzOption("->"), TikzOption("thick")],
    )
