"""
Generate Operation Definition Language (ODL) from the 10k mapping plan.

This script parses the `universal_mapping.json` generated by `generate_10k_plan.py`
and generates corresponding ODL YAML files that ml-switcheroo can ingest directly.
It handles direct mappings and automatic fallback decomposition using the JAX intermediate plugin.
"""

import json
from pathlib import Path
import yaml

MAPPING_FILE = Path("universal_mapping.json")
OUTPUT_FILE = Path("docs/generated_operations.yaml")


def generate_odl() -> None:
  """Reads the universal mapping and writes ODL blocks to YAML."""
  if not MAPPING_FILE.exists():
    print(f"Mapping file {MAPPING_FILE} not found. Run generate_10k_plan.py first.")
    return

  with MAPPING_FILE.open("r", encoding="utf-8") as f:
    data = json.load(f)

  # We want to group by source operation to create universal ODL nodes
  # Right now, data is grouped by "src_to_dst". We need to invert it.
  operations = {}

  for phase_name, ops in data.items():
    if not phase_name.endswith("_to_keras"):  # Just an example phase
      continue

    src, dst = phase_name.split("_to_")
    for src_op, meta in ops.items():
      op_name = src_op.split(".")[-1]

      if op_name not in operations:
        operations[op_name] = {
          "operation": op_name,
          "description": f"Auto-generated mapping for {op_name}.",
          "op_type": "function",
          "std_args": [],
          "variants": {src: {"api": src_op}},
        }

      if meta["type"] == "direct":
        operations[op_name]["variants"][dst] = {"api": meta["target"]}
      elif meta["type"] == "decompose":
        intermediate = meta["intermediate"]
        operations[op_name]["variants"][dst] = {
          "requires_plugin": "jax_decompose",
          "missing_message": f"Decomposed via {intermediate} AST transpilation.",
        }

  output_list = list(operations.values())

  # Write to file
  with OUTPUT_FILE.open("w", encoding="utf-8") as f:
    yaml.dump(output_list, f, sort_keys=False, default_flow_style=False)

  print(f"Generated {len(output_list)} ODL definitions in {OUTPUT_FILE}")


if __name__ == "__main__":
  generate_odl()
