
?start: module
module: (operation | attribute_alias_def)*

operation: [results EQ] custom_operation

custom_operation: op_name [SYM_ID] [operands] [dictionary_attribute] op_tail*

attribute_alias: ATTR_ALIAS_ID
attribute_alias_def: attribute_alias EQ attribute_value

?op_tail: regions | COLON result_types | ARROW result_types

results: VAL_ID (COMMA VAL_ID)*
op_name: IDENTIFIER | STRING | SYM_ID
bare_id_list: IDENTIFIER (COMMA IDENTIFIER)*

operands: LPAREN [operand_list] RPAREN
| LPAREN DOT DOT DOT RPAREN
| operand_list
operand_list: operand (COMMA operand)*

operand: (VAL_ID | SYM_ID) [COLON TYPE]

dictionary_attribute: LBRACE [attribute_entry (COMMA attribute_entry)*] RBRACE
attribute_entry: attr_name EQ attribute_value
attr_name: IDENTIFIER | STRING
attribute_value: STRING | NUMBER | decimal_literal | TYPE | type_list_parens | function_type | LBRACK [attribute_value (COMMA attribute_value)*] RBRACK | attribute_alias | IDENTIFIER | dialect_attribute
decimal_literal: NUMBER

dialect_attribute: ATTR_ALIAS_ID (OPAQUE_DIALECT_CONTENTS | DOT IDENTIFIER)

regions: region+
region: LBRACE block* RBRACE

block_label: block_id [block_arg_list] COLON
block: [block_label] operation*
block_arg_list: LPAREN [block_arg (COMMA block_arg)*] RPAREN
block_arg: VAL_ID COLON TYPE
block_id: CARET_ID

result_types: TYPE
| LPAREN [TYPE (COMMA TYPE)*] RPAREN
| LPAREN [TYPE (COMMA TYPE)*] RPAREN ARROW TYPE
| LPAREN [TYPE (COMMA TYPE)*] RPAREN ARROW LPAREN [TYPE (COMMA TYPE)*] RPAREN

// Missing grammar rules from LangRef
dialect_type: "!" (opaque_dialect_type | pretty_dialect_type)
dialect_type_body: LANGLE dialect_type_contents+ RANGLE
dialect_type_contents: dialect_type_body | IDENTIFIER
dictionary_properties: LANGLE dictionary_attribute RANGLE
entry_block: operation+
function_type: (TYPE | type_list_parens) ARROW (TYPE | type_list_parens)
generic_operation: STRING [LPAREN value_use_list RPAREN] [successor_list]
op_result: VAL_ID [COLON NUMBER]
op_result_list: op_result (COMMA op_result)* EQ
opaque_dialect_attribute: dialect_namespace dialect_attribute_body
opaque_dialect_type: dialect_namespace dialect_type_body
pretty_dialect_attribute: dialect_namespace DOT pretty_dialect_attribute_lead_ident
pretty_dialect_attribute_lead_ident: IDENTIFIER
pretty_dialect_type: dialect_namespace DOT pretty_dialect_type_lead_ident
pretty_dialect_type_lead_ident: IDENTIFIER
region_list: LPAREN region (COMMA region)* RPAREN
ssa_use: value_use
ssa_use_and_type: ssa_use COLON TYPE
ssa_use_and_type_list: ssa_use_and_type (COMMA ssa_use_and_type)*
successor: CARET_ID [COLON block_arg_list]
successor_list: LBRACK successor (COMMA successor)* RBRACK
trailing_location: "loc" LPAREN STRING RPAREN
type_alias: "!" IDENTIFIER
type_alias_def: type_alias EQ TYPE
type_list_no_parens: TYPE (COMMA TYPE)*
type_list_parens: LPAREN [TYPE (COMMA TYPE)*] RPAREN
value_id_and_type: VAL_ID COLON TYPE
value_id_and_type_list: value_id_and_type (COMMA value_id_and_type)*
value_id_list: VAL_ID (COMMA VAL_ID)*
value_use: VAL_ID [ATTR_ALIAS_ID NUMBER]
value_use_list: value_use (COMMA value_use)*
dialect_namespace: IDENTIFIER
dialect_attribute_body: LANGLE dialect_attribute_contents+ RANGLE
dialect_attribute_contents: dialect_attribute_body | IDENTIFIER

digit: /[0-9]/
hex_digit: /[0-9a-fA-F]/
hexadecimal_literal: /0x[0-9a-fA-F]+/
id_punct: /[$._-]/
letter: /[a-zA-Z]/
suffix_id: /[0-9]+|([a-zA-Z$._-][a-zA-Z0-9$._-]*)/

EQ: "="
COMMA: ","
LPAREN: "("
RPAREN: ")"
LBRACE: "{"
RBRACE: "}"
LBRACK: "["
RBRACK: "]"
COLON: ":"
ARROW: "->"
LANGLE: "<"
RANGLE: ">"
DOT: "."

VAL_ID: /%./
SYM_ID: /@./
ATTR_ALIAS_ID: /#./
TYPE: /!./
NUMBER: /1/
STRING: /"."/
OPAQUE_DIALECT_CONTENTS: /<./
IDENTIFIER: /a/
CARET_ID: /\^./
