?start: module

module: trivia? (operation | attribute_alias_def)* trivia?

trivia: (WS | COMMENT)+

operation: results_clause? (IDENTIFIER | STRING) trivia? operands_clause? attributes_clause? regions_clause? types_clause? trivia?

attribute_alias_def: ATTR_ALIAS_ID trivia? "=" trivia? attribute_value trivia?

results_clause: results trivia? "=" trivia?
operands_clause: operands trivia?
attributes_clause: attributes trivia?
regions_clause: regions trivia?
types_clause: ":" trivia? types

results: VAL_ID (trivia? "," trivia? VAL_ID)*
operands: "(" trivia? [VAL_ID (trivia? "," trivia? VAL_ID)* trivia?] ")" | VAL_ID (trivia? "," trivia? VAL_ID)*
attributes: "{" trivia? attribute (trivia? "," trivia? attribute)* trivia? "}"
attribute: IDENTIFIER trivia? "=" trivia? attribute_value
attribute_value: STRING | NUMBER | TYPE | array_attr | ATTR_ALIAS_ID
array_attr: "[" trivia? [NUMBER (trivia? "," trivia? NUMBER)* trivia?] "]"

regions: region (trivia? region)*
region: "{" trivia? block* "}"

block: block_label_clause? operation*
block_label_clause: BLOCK_LABEL trivia? block_args_clause? ":" trivia?
block_args_clause: "(" trivia? block_arg_list trivia? ")" trivia?

block_arg_list: block_arg (trivia? "," trivia? block_arg)*
block_arg: VAL_ID trivia? ":" trivia? TYPE

types: TYPE | "(" trivia? [TYPE (trivia? "," trivia? TYPE)* trivia?] ")" trivia? ["->" trivia? (TYPE | "(" trivia? [TYPE (trivia? "," trivia? TYPE)* trivia?] ")")]

VAL_ID: /%[a-zA-Z_0-9]+/ | /%\d+/
BLOCK_LABEL: /\^[a-zA-Z_0-9]+/
SYM_ID: /@[a-zA-Z_0-9]+/
ATTR_ALIAS_ID: /#[a-zA-Z_0-9$._-]+/
IDENTIFIER: /[a-zA-Z_][a-zA-Z0-9_$.]*|"[^"]+"/ | SYM_ID
STRING: /"(?:[^"\\]|\\.)*"/
TYPE: /![a-zA-Z_0-9\.<>]+/ | /!sw\.type<[^>]+>/ | /tensor<[^>]+>/ | /[iuf]\d+/ | "index" | "none"
NUMBER: /-?\d+(?:\.\d+)?/

COMMENT: /\/\/[^\n]*/
WS: /[ \t\f\r\n]+/
