"""Coverage tests for the C++ compiler backend parser and AST transformer.

This test module verifies the parse logic, token transformation, and AST node
structure generated by the CppParser and CppTransformer classes. It exercises
syntactic edge cases, branch logic fallback paths, and syntax errors to achieve
complete unit coverage of the C++ parsing capabilities.
"""

import pytest

from ml_switcheroo.core.compiler.backends.cpp.cst import CppModule
from ml_switcheroo.core.compiler.backends.cpp.parser import CppParser


def test_parser_coverage() -> None:
  """Verifies C++ parser coverage across edge cases and error conditions.

  This test covers:
  - Mismatch scenarios where syntax errors trigger expected ValueErrors.
  - Parsing a raw statement with custom body size.
  - Correct identification of an empty macro definition.
  - Including system headers with angle brackets.
  - Return statements with empty, string, or numeric values.
  - Variable declarations initialized with custom expressions.
  - Missing reference/fallback failures in Pybind11 modules.

  Args:
      None.

  Returns:
      None.
  """
  # MISMATCH
  with pytest.raises(ValueError, match="Unexpected"):
    CppParser("¿").parse()

  with pytest.raises(ValueError, match="Unexpected"):
    CppParser("(").parse()

  with pytest.raises(ValueError, match="Unexpected"):
    CppParser("int (").parse()

  with pytest.raises(ValueError, match="Unexpected"):
    CppParser("int foo {").parse()

  with pytest.raises(ValueError, match="Unexpected"):
    CppParser("int foo").parse()

  with pytest.raises(ValueError, match="Unexpected"):
    CppParser("+").parse()

  # Raw statement
  parser = CppParser("int foo() { some_code_here; }")
  mod: CppModule = parser.parse()
  assert len(mod.body) == 1

  # Empty macro
  parser = CppParser("#define FOO")
  mod = parser.parse()
  assert getattr(mod.body[0], "value") == ""

  # Include with angle brackets
  parser = CppParser("#include <vector>")
  mod = parser.parse()
  assert mod.includes[0].path == "vector"
  assert mod.includes[0].system is True

  # Return statement empty
  parser = CppParser("int f() { return ; }")
  mod = parser.parse()
  assert getattr(mod.body[0], "body")[0].value is None

  # Return string and number expression
  parser = CppParser('int f() { return "hello"; return 42; }')
  mod = parser.parse()
  assert getattr(getattr(mod.body[0], "body")[0].value, "name", None) == '"hello"'
  assert getattr(getattr(mod.body[0], "body")[1].value, "name", None) == "42"

  # Variable decl with expression
  parser = CppParser("int f() { int x = 5; }")
  mod = parser.parse()
  assert getattr(getattr(mod.body[0], "body")[0].initializer, "name", None) == "5"

  # Pybind missing ref error / fallback
  with pytest.raises(ValueError, match="Unexpected"):
    CppParser('PYBIND11_MODULE(m1, m2) { m.def("a", foo, "doc"); }').parse()


def test_missing_coverage() -> None:
  """Tests parsing scenarios covering remaining gaps in AST node types.

  This includes validation of:
  - Macro defines with empty bodies.
  - Invalid include directive syntax that raises a ValueError.
  - Incorrect Pybind11 module declarations without reference qualifiers.
  - Declarations of uninitialized local variables.
  - Void returns.
  - Function calls utilized as initializers in variable declarations.
  - Empty source code parsing resulting in an empty module body.

  Args:
      None.

  Returns:
      None.
  """
  # Test macro with no value
  assert getattr(CppParser("#define FOO").parse().body[0], "value", None) == ""

  # Test include missing system true/false fallback (invalid syntax technically)
  with pytest.raises(ValueError):
    CppParser("#include foo").parse()

  # Test pybind with & using identifier directly
  parser = CppParser('PYBIND11_MODULE(m, m) { m.def("a", foo, "doc"); }')
  with pytest.raises(ValueError):
    parser.parse()  # we expect &

  # Test variable decl with no initializer
  mod: CppModule = CppParser("int foo;").parse()
  assert getattr(mod.body[0], "name", None) == "foo"

  # Test return empty
  mod = CppParser("return;").parse()
  assert getattr(mod.body[0], "value", None) is None

  # Test method call expression inside variable decl
  mod = CppParser("int foo = bar(1);").parse()
  assert getattr(getattr(mod.body[0], "initializer", None), "name", None) == "bar"

  # test module empty
  assert len(CppParser("").parse().body) == 0


def test_missing_coverage_3() -> None:
  """Verifies specific AST structure generation for functions and variables.

  Tests coverage for:
  - Function argument parsing with multiple typed arguments.
  - Extraction of second module arguments within Pybind11 module blocks.
  - Return statements lacking return expressions within function scopes.
  - Binary operator expression handling with multiple string literals.

  Args:
      None.

  Returns:
      None.
  """
  # Include fallback (although parsing should catch it, transformer has a return path)
  # func_args, func_arg
  mod: CppModule = CppParser("int foo(int x, float y) {}").parse()
  assert getattr(mod.body[0], "arguments")[1].name == "y"

  # pybind module_var assignment
  mod = CppParser("PYBIND11_MODULE(m1, m2) {}").parse()
  assert getattr(mod.body[0], "module_var", None) == "m2"

  # return empty
  mod = CppParser("int f() { return; }").parse()
  assert getattr(getattr(mod.body[0], "body")[0], "value", None) is None

  # binary expr and string lit
  mod = CppParser('int x = "a" + "b";').parse()
  assert getattr(getattr(mod.body[0], "initializer", None), "operator", None) == "+"


def test_missing_coverage_4() -> None:
  """Verifies parsing of macro literals and local header include paths.

  Validates:
  - Defining macros with string and numeric values.
  - Including local header files using double quotes (system is False).

  Args:
      None.

  Returns:
      None.
  """
  # macro define with value string
  mod: CppModule = CppParser('#define FOO "bar"').parse()
  assert getattr(mod.body[0], "name", None) == "FOO"

  # macro define with number
  mod = CppParser("#define FOO 42").parse()
  assert getattr(mod.body[0], "name", None) == "FOO"

  # local include
  mod = CppParser('#include "local.h"').parse()
  assert mod.includes[0].system is False


def test_missing_coverage_unreachable() -> None:
  """Validates AssertionError triggers on unreachable transformer logic.

  Directly invokes internal transformer methods with invalid structures to
  confirm assertion-based guards for include translation function paths.

  Args:
      None.

  Returns:
      None.
  """
  from ml_switcheroo.core.compiler.backends.cpp.parser import CppTransformer

  t = CppTransformer()
  with pytest.raises(AssertionError):
    t.include_system([])
  with pytest.raises(AssertionError):
    t.include_local([])


def test_cpp_parser_branch_coverage() -> None:
  """Tests CppTransformer branch paths using raw token list structures.

  Directly exercises internal transformer class methods with edge-case
  and incomplete lists of Lark tokens to ensure robust fallback logic for:
  - Function definitions with missing identifiers.
  - Function arguments with missing identifiers.
  - Pybind definitions with missing variables.
  - Variable declarations missing identifiers or expressions.
  - Binary expressions missing operators or punctuators.

  Args:
      None.

  Returns:
      None.
  """
  from lark import Token

  from ml_switcheroo.core.compiler.backends.cpp.parser import CppTransformer

  transformer = CppTransformer()

  # 131->136 function missing identifier
  f = transformer.function(["type_id", Token("PUNCT", "(")])
  assert getattr(f, "name", None) == ""

  # 154->158 func_arg missing identifier
  fa = transformer.func_arg(["type_id", Token("PUNCT", ",")])
  assert getattr(fa, "name", None) == ""

  # 170->177 pybind missing second identifier
  pb = transformer.pybind([Token("IDENTIFIER", "module_name")])
  assert getattr(pb, "module_var", None) == ""

  # 213->217 var_decl_init missing identifier
  # 218->222 var_decl_init missing expression
  vd = transformer.var_decl_init(["type_id", Token("PUNCT", "=")])
  assert getattr(vd, "name", None) == ""
  assert getattr(vd, "initializer", None) is None

  # 255->259 binary_expr missing punct
  from ml_switcheroo.core.compiler.backends.cpp.cst import Identifier

  be = transformer.binary_expr([Identifier("a"), Identifier("b")])
  assert getattr(be, "operator", None) == ""
