"""Test suite for the Tikz Parser module."""

import typing

from ml_switcheroo.core.compiler.ir import LogicalGraph
from ml_switcheroo.core.tikz.parser import TikzParser, _logical_from_tikz_graph

SAMPLE_TIKZ = "\n% Generated by ml-switcheroo\n\\begin{tikzpicture}[node distance=2cm, auto]\n    \\node [draw, fill=blue!5] (conv1) at (0, 0) {\n        \\begin{tabular}{c}\n            \\textbf{Conv2d} \\\\\n            \\textit{conv1} \\\\\n            kernel: 3 \\\\\n            out: 64 \\\\\n        \\end{tabular}\n    };\n\n    \\node [draw, fill=red!10] (output) at (0, -3) {\n        \\begin{tabular}{c}\n            \\textbf{Output} \\\\\n            \\textit{output} \\\\\n        \\end{tabular}\n    };\n\n    \\draw [->, thick] (conv1) -- (output);\n\\end{tikzpicture}\n"


def test_parser_nodes_extraction() -> None:
  """Docstring."""
  parser = TikzParser(SAMPLE_TIKZ)
  graph: LogicalGraph = _logical_from_tikz_graph(parser.parse())
  assert len(graph.nodes) == 2
  conv: typing.Any = next((n for n in graph.nodes if n.id == "conv1"))
  assert conv.kind == "Conv2d"
  assert conv.metadata["kernel"] == "3"
  assert conv.metadata["out"] == "64"
  out: typing.Any = next((n for n in graph.nodes if n.id == "output"))
  assert out.kind == "Output"
  assert out.metadata == {}


def test_parser_edges_extraction() -> None:
  """Docstring."""
  parser = TikzParser(SAMPLE_TIKZ)
  graph: LogicalGraph = _logical_from_tikz_graph(parser.parse())
  assert len(graph.edges) == 1
  edge: typing.Any = graph.edges[0]
  assert edge.source == "conv1"
  assert edge.target == "output"


def test_parser_ignore_comments_and_env() -> None:
  """Verifies the behavior of parser ignore comments and environment."""
  code: str = "\n% Comment\n\\begin{tikzpicture}\n    % Node Comment\n    \\node (a) at (0,0) {A};\n\\end{tikzpicture}\n"
  parser = TikzParser(code)
  graph: LogicalGraph = _logical_from_tikz_graph(parser.parse())
  assert len(graph.nodes) == 1
  assert graph.nodes[0].id == "a"
  assert graph.nodes[0].kind == "A"


def test_parser_robust_metadata() -> None:
  """Verifies the behavior of parser robust metadata."""
  code: str = "\n\\node (n) at (0,0) {\n    \\begin{tabular}{c}\n        \\textbf{Layer} \\\\\n        \\textit{n} \\\\\n        kernel\\_size: (3, 3) \\\\\n    \\end{tabular}\n};\n"
  parser = TikzParser(code)
  graph: LogicalGraph = _logical_from_tikz_graph(parser.parse())
  node: typing.Any = graph.nodes[0]
  assert "kernel_size" in node.metadata
  assert node.metadata["kernel_size"] == "(3, 3)" or "3" in node.metadata["kernel_size"]
